- Maestro/subscriptions.json
This happens whenever a new CLI build is completed.  The referenced build definition simply makes the appropriate http put request to Docker Hub that will trigger the build.  Maybe at some time in the future Maestro will have support for this type of action rather than needing to use a VSO build definition.
@eerhardt - not sure how to test this change.  Please advise.
> Added subscription to trigger building dotnet-preview Docker image

- Maestro/subscriptions.json
Adds a subscription that updates the new dependency version categories that will be created in https://github.com/dotnet/corefx/pull/8999.
~~It's a bit repetitive. `UpdateDependencies.ps1` could be updated to allow for an array of elements to update, but doing it this way makes it easier to split them off later.~~ (Added array support.)
/cc @eerhardt @weshaggard
> Add CoreFX subscriptions for ProjectK TFS build

- Maestro/subscriptions.json
Now there are CoreFX (build pipeline), External (TFS) and CoreCLR (from its build pipeline).
Separating these out now because the CoreCLR build pipeline is turning on.
/cc @eerhardt @weshaggard @wtgodbe
> Separate out CoreFX dependency subscriptions

- build-info/dotnet/roslyn/netcore1.0/Latest_Packages.txt
Update Roslyn NuGet versions to 1.3.0-beta1-20160602-01.
> Update Roslyn versions

- Maestro/subscriptions.json
Matches update in https://github.com/dotnet/corefx/pull/9111 (bringing in the change from CoreFX master).
/cc @eerhardt @jhendrixMSFT
> Update CoreFX 1.0.0 subscription's CoreFxVersionUrl to VersionFileUrl.

- Maestro/subscriptions.json
Added build definitions and subscriptions for CoreCLR dependency auto-update.
Will run the scripts being added in:
* https://github.com/dotnet/coreclr/pull/5636 (master)
* https://github.com/dotnet/coreclr/pull/5637 (release/1.0.0)
It looks like @dotnet/coreclr-contrib doesn't exist. Should we make it so there's an obvious group who gets notifications for these PRs?
/cc @gkhanna79 @eerhardt @weshaggard
> Add subscription for CoreCLR External dependencies

- Maestro/subscriptions.json
With the non-raw GitHub url, the update script was adding random HTML into `dir.props`, which fails the auto-PR build. This only happened for recent release builds because when I made those I copy-pasted the subscription `path` into the `VersionFileUrl` parameter without spotting that critical difference.
Fixes https://github.com/dotnet/versions/issues/24, although we should still stop doing native builds in the auto-update build just because it's unnecessary.
/cc @jhendrixMSFT @eerhardt @joshfree
> Fix VersionFileUrl parameters to get raw github content

- Maestro/subscriptions.json
The dotnet-preview has been renamed to dotnet-nightly.  It also is now using the rel/1.0.0 release train.
Fixes https://github.com/dotnet/dotnet-docker-nightly/issues/22 and fixes https://github.com/dotnet/dotnet-docker-nightly/issues/14.
cc: @eerhardt @MichaelSimons
> Update Docker Hub build handler

- Maestro/subscriptions.json
https://github.com/dotnet/versions/pull/39 used the default value from https://github.com/dotnet/corefx/blob/master/UpdateDependencies.ps1, which meant the PR was for dev/api commits with the upgrade commit on top.
Example PR: https://github.com/dotnet/corefx/pull/10161
/cc @eerhardt @stephentoub
> Make upgrade PRs for dev/api against dev/api, not the default master.

- Maestro/subscriptions.json
Reverts the projectk-tfs part of https://github.com/dotnet/versions/pull/43 to keep coreclr updated.
/cc @eerhardt @gkhanna79
> Keep projectk-tfs -> coreclr auto-updates enabled

- Maestro/subscriptions.json
Now that `vsoSourceBranch` exists, the extra per-branch definitions aren't needed.
/cc @eerhardt @gkhanna79
> Add coreclr->corefx 1.0.0 subscription; clean up unnecessary defs

- Maestro/subscriptions.json
The new command looks like:
```
build-managed.cmd -- /t:UpdateDependencies
/p:GitHubUser=dotnet-bot
/p:GitHubEmail=dotnet-bot@microsoft.com
/p:GitHubAuthToken=...
/p:ProjectRepoOwner=dotnet
/p:ProjectRepoName=corefx
/p:ProjectRepoBranch=master
/p:NotifyGitHubUsers="dotnet/corefx-contrib"
```
`UpdateDependencies` updates all corefx dependencies at the same time (to put it in the same PR) so the same command happens no matter which dependency changes. (Ripe for a refactor into multiple paths per subscription!)
When the VersionTools changes get merged into `dev/api` I'll need to change the subscription for that branch too.
/cc @weshaggard @eerhardt
> Change all "into CoreFX master" subscriptions to new VersionTools build task

- Maestro/subscriptions.json
@gkhanna79 This disables PRs like https://github.com/dotnet/corefx/pull/10663, which are unnecessary right now and fail.
If we start servicing any External packages that need to be referenced in CoreFX, this PR can be reverted.
> Disable projectk-tfs release/1.0.0 (KRel) -> CoreFX release/1.0.0 auto-upgrade

- Maestro/subscriptions.json
Without this it ends up calling:
[VSTS inline script].ps1 ... -Arguments "-- ... /p:NotifyGitHubUsers="dotnet/corefx-contrib""
This ignores the "extra" stuff after what it sees as the closing `"` after `=`. I'm not sure what powershell is doing with it that makes this not a syntax error. Escaping the `"` makes it not close the string.
Does this look right, @eerhardt?
I want to keep the quotes because this can become a list by adding `;` and I don't want someone else to potentially have to figure it out later.
> Escape quotes after /p:NotifyGitHubUsers= to avoid powershell arg behavior

- Maestro/subscriptions.json
There's no need to notify multiple users, so this removes my earlier attempt to escape `"`'s to make it possible. If we want to notify multiple users later, it can be done in the `dir.props` of the respective repo along with the upgrade config. It could be done with a bunch of escaping but it's overly confusing.
See https://github.com/dotnet/versions/pull/50 for details about the escaping problem. (cc @eerhardt @jaredpar)
> Remove quotes from NotifyGitHubUsers to avoid excessive escaping

- Maestro/subscriptions.json
Use the update-dependencies app to update the CLI versions in the
Dockerfiles.  This will trigger DockerHub builds, so the
build-dotnet-docker-nightly action is no longer needed.
cc: @eerhardt @MichaelSimons
> Update dotnet-docker-nightly subscription

- Maestro/subscriptions.json
Accompanies https://github.com/dotnet/coreclr/pull/6664, will merge this after.
`run.cmd build -Project=tests\build.proj -- /t:UpdateDependenciesAndSubmitPullRequest ...` is now used to update coreclr dependencies.
Adds back the CoreCLR and CoreFX dependency updates because now they'll update a single PR when possible instead of sending a flood of them.
@gkhanna79 @wtgodbe @eerhardt 
FYI, @jkotas, that these upgrades will start happening. (I thought you might be interested since you raised the concern about the PR flood a while back.)
> Use new update command in coreclr; add corefx, coreclr subscriptions

- Maestro/subscriptions.json
This avoids powershell argument parsing behavior where in `-Project=tests\build.proj`, `-Project=tests\build` is considered the argument name and `.proj` is considered a separate argument. The result was a space "appearing" in the list of args when the command is executed.
This behavior is visible in the coloring shown in the powershell console: names are gray and args are white. Quoting seems to make powershell treat the entire `-Project='tests\build.proj'` string as a single argument (white).
Fixes errors like in [this build](https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_build/index?buildId=301219&_a=summary): "Error: Parameter not recognized: .proj.", and coreclr auto-upgrade should start working.
(This is only a problem when running from powershell, not a cmd terminal. `"` …
> Surround tests\build.proj for coreclr auto-upgrade with single quotes

- Maestro/subscriptions.json
This subscription will kick off an official "pipebuild" of the core-setup
repo per commit into the master branch of the core-setup repo.
> Add a subscription to the core-setup master branch for official builds.

- Maestro/subscriptions.json
Preparation for auto-publishing of NETNative targeting pack from ProjectN. Create a blank build-info for the auto-publish to fill in and a subscription for corefx dev/api. (I forgot the subscription part when I was talking with you about this, @sedarg.)
This new build-info will include `Microsoft.TargetingPack.Private.NETNative` from ProjectN. I'll be making a manual change to remove this package from `projectk-tfs/Latest_Packages.txt` so auto-upgrade won't hit a conflict. @sedarg is making ProjectK no longer publish that package for future builds.
/cc @eerhardt @sedarg
> Create build-info for ProjectN auto-publish, add dev/api subscription

- build-info/dotnet/projectk-tfs/master/Latest_Packages.txt
Remove projectk-tfs version of the NETNative targeting pack. Follows up on https://github.com/dotnet/versions/pull/60. I thought I would want to order this PR later, but it turns out it's more helpful to do it now.
(This package won't be in projectk-tfs in the next build, this manual change just unblocks some PRs.)
/cc @SedarG @eerhardt
> Remove projectk-tfs NETNative targeting pack: moving to projectn-tfs

- Maestro/subscriptions.json
The default verbosity is Minimal, which hides most messages and makes it hard to debug a failure in a Maestro-triggered build.
/cc @eerhardt @weshaggard
> Override Run.cmd verbosity to Normal to see logged messages

- Maestro/subscriptions.json
Adds corefx and core-setup release/1.1.0 subscriptions:
* corefx, coreclr -> corefx (all release/1.1.0)
* ProjectK TFS (master) -> corefx (release/1.1.0)
* corefx, coreclr -> core-setup (all release/1.1.0)
* roslyn (1.0.0, "netcore1.0") -> core-setup (release/1.1.0)
These are based on what the subscriptions were for the master branch, except for core-setup. The roslyn core-setup subscription is based on 1.0.0 because core-setup doesn't have master branch subscriptions.
Should wait for:
* ~~https://github.com/dotnet/coreclr/pull/7109~~
Otherwise, some auto-PR attempts might be made that result in weird PRs or errors in Maestro executor builds.
@gkhanna79 @weshaggard @eerhardt
> Add release/1.1.0 subscriptions

- Maestro/src/Microsoft.DotNet.Maestro.WebApi/Controllers/CommitPushedController.cs
- Maestro/src/Microsoft.DotNet.Maestro.WebApi/Microsoft.DotNet.Maestro.WebApi.csproj
- Maestro/src/Microsoft.DotNet.Maestro.WebApi/Services/VerifyPayloadSignatureAttribute.cs
- Maestro/src/Microsoft.DotNet.Maestro.WebApi/Web.config
- Maestro/src/Microsoft.DotNet.Maestro/Config.cs
When Maestro receives an HTTP request, verify that it's from an
authorized source and wasn't corrupted by comparing the payload
signature to the HMAC calculated from the HTTP request's content with
the webhook's secret token as the key.
cc: @eerhardt @bartonjs
> Verify payload signatures from webhooks

- Maestro/subscriptions.json
I said earlier that core-setup builds on commit, but I saw merging a PR that it's only for master. This should add a trigger for release/1.1.0.
I don't think leaving core-setup to be manually queued is a good idea because only one build is possible per commit. Automatically triggering will make sure nobody accidentally queues twice on the same one.
@eerhardt There's no extra per-branch setup in the core-setup repo settings, right?
/cc @gkhanna79 @weshaggard @wtgodbe @ianhays
> Add subscription to trigger core-setup 1.1.0 builds

- Maestro/subscriptions.json
* corefx, coreclr -> coreclr (all release/1.1.0)
This depends on merging https://github.com/dotnet/coreclr/pull/7109 which sets up coreclr/release/1.1.0's build-info dependencies.
@gkhanna79 @eerhardt
> Add coreclr release/1.1.0 subscriptions

- Maestro/subscriptions.json
CoreFx/dev/api has been merged into CoreFX/master and the development will continue on master, rather than dev/api. we need to update the subscription of ProjectN-tfs feed to also update the master branch. 
@dagood , @eerhardt , could you please take a look
> adding a subscription to corefx/master for ProjectN-tfs feed

- Maestro/subscriptions.json
This lets MyGet get the packages ready: there may be a delay before they can be downloaded which causes restore errors in CI.
The other auto-PRs already do this--I just didn't think to add it when copying over the core-setup auto-PR subscription from master to release/1.1.0. This should fix the restore errors we saw on a few auto-PRs that we worked around by rerunning CI.
@gkhanna79 @wtgodbe
> Delay core-setup PRs 10 minutes

- Maestro/subscriptions.json
The branch is no longer being used or built, so these are unnecessary.
@joperezr @weshaggard
> Disable corefx dev/api subscriptions

- Maestro/subscriptions.json
This will enable auto-PRs on core-setup when a 1.0.0 branch coreclr build completes.
@gkhanna79
> Add coreclr -> core-setup 1.0.0 subscription

- Maestro/subscriptions.json
Latest_Packages.txt results in the old auto-update code in corefx release/1.0.0 trying to put the full list of packages into the corefx expected prerelease msbuild property.
I believe the value in the text file is also used in the PR title, causing errors like in https://devdiv.visualstudio.com/DevDiv/_build?buildId=360738 because of the newlines.
Also updates DirPropsVersionElements to `CoreFxExpectedPrerelease` (from `ExternalExpectedPrerelease`), so the correct upgrade happens. It looks like this handler was copy-pasted without enough modifications.
> Use Latest.txt in corefx release/1.0.0

- Maestro/subscriptions.json
Remove notifications of coreclr/corefx-contrib groups because of they are not useful
> Remove notifications of coreclr/corefx-contrib groups

- Maestro/subscriptions.json
This dependency no longer exists with https://github.com/dotnet/coreclr/pull/7714 merged.
@gkhanna79
> Remove CoreCLR master auto-update from ProjectK

- Maestro/README.md
- Maestro/src/Microsoft.DotNet.Maestro.WebApi/Microsoft.DotNet.Maestro.WebApi.csproj
- Maestro/src/Microsoft.DotNet.Maestro.WebApi/Models/ActionList.cs
- Maestro/src/Microsoft.DotNet.Maestro.WebApi/Models/Subscription.cs
- Maestro/src/Microsoft.DotNet.Maestro.WebApi/Models/SubscriptionsModel.cs
- Maestro/src/Microsoft.DotNet.Maestro.WebApi/Services/HandlerResolver.cs
- Maestro/src/Microsoft.DotNet.Maestro/Handlers/VsoBuildHandler.cs
- Maestro/src/Microsoft.DotNet.Maestro/Microsoft.DotNet.Maestro.csproj
- Maestro/src/Microsoft.DotNet.Maestro/Models/HandlerObject.cs
- Maestro/src/Microsoft.DotNet.Maestro/Services/VsoParameterGenerator.cs
- Maestro/subscriptions.json
- Maestro/test/Microsoft.DotNet.Maestro.SubscriptionValidation/SubscriptionValidationTests.cs
- Maestro/test/test-subscriptions.json
This reverts commits a89a6d79, 25f4f7b4, and c99e4841.
The Maestro web app has not been published to Azure since making these
changes, so the published app is out of sync with the
subscriptions.json in this repo.  With eerhardt out, we need to decide
our plan for publishing Maestro; in the meantime, the changes are being
reverted to get it back in sync.
/cc @dagood
> Revert changes to refactor subscriptions.json

- Maestro/subscriptions.json
This change is need for https://github.com/dotnet/dotnet-docker-nightly/pull/103
@dagood
> Update Docker subscriptions to specify the CLI_RELEASE_MONIKER

- Maestro/subscriptions.json
This will make it so builds don't accidentally get triggered while the 1.1.0 branch is in the fragile stable state.
@gkhanna79
> Remove core-setup release/1.1.0 commit build trigger

- Maestro/subscriptions.json
Adds upgrade auto-PR subscriptions for core-setup master branch.
Also fixes the existing release/1.0.0 subscriptions. The subscriptions were assuming that core-setup-general defaults to the master branch, but it actually defaults to release/1.0.0.
@gkhanna79 @brianrob
> Add core-setup master auto-PR trigger

- build-info/dotnet/projectk-tfs/release/1.0.0/Latest.txt
- build-info/dotnet/projectk-tfs/release/1.0.0/Latest_Packages.txt
The auto-publish build successfully pushed the package, but failed to update the versions repo: https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=421214
The versions repo update failure was because auto-publish assumed there would be a prerelease package it could harvest the value from, but there wasn't. I changed the publish script to use `stable` in this case rather than throwing an exception. This matches https://github.com/dotnet/buildtools/pull/1174.
@gkhanna79 @weshaggard
> Fix projectk/release/1.0.0 build-info to match stable 1.0.x build

- Maestro/subscriptions.json
When creating a CoreCLR auto-update PR, notify @dotnet/coreclr-auto-update-notify.
See https://github.com/dotnet/coreclr/pull/8582#issuecomment-267163144.
Partially reverts #91, but uses a new fine-grained group that members are free to leave/join. (https://github.com/orgs/dotnet/teams/coreclr-auto-update-notify)
> Add coreclr auto-update PR notifications

- Maestro/subscriptions.json
Now that core-setup release/1.0.0 and release/1.1.0 produce prereleases, enable automatic builds because they aren't dangerous anymore.
@gkhanna79
> Add subscription to trigger core-setup release builds on commit

- Maestro/subscriptions.json
We don't use these auto-PRs at the moment in the CLI. So turning this functionality off.
@dagood @naamunds 
/cc @livarcocc
> Remove CLI update dependencies subscription

- Maestro/subscriptions.json
With SNI builds running, there is build-info being generated an published to the dotnet/versions repo.
This change adds the change to subscriptions.json so that SNI versions can be published to .Net Corefx repo.
cc @dagood
> Adding SNI subscription to Maestro

- Maestro/subscriptions.json
I had an incorrect URL for the trigger path in the CLI subscription.
@MichaelSimons @dagood @naamunds
> Fix CLI trigger path

- Maestro/subscriptions.json
The removed subscriptions are no longer need as a result of https://github.com/dotnet/dotnet-docker-nightly/commit/beadabea1aa5a7b8f34f2c5952970377623cef88.
> Switch Docker to devdiv build definition and cleanup unused subscriptions

- build-info/dotnet/corefx/release/1.1.0/Latest.txt
- build-info/dotnet/corefx/release/1.1.0/Latest_Packages.txt
This reverts commits 63eeda89c687d359d42cb6f824c2a2fcaf459fcf and 7a70e49511fdf08fb99b98d92dbdcbd0d75c5952, created when an unintentional corefx 1.1.0 build happened. I put the packages from the earlier build back in place on MyGet, and this PR makes the dotnet/versions repo consistent with the rollback.
See https://github.com/dotnet/coreclr/pull/9708
@gkhanna79 @MattGal
> Revert corefx/release/1.1.0 build-info update

- Maestro/subscriptions.json
These changes support https://github.com/dotnet/dotnet-docker-nightly/pull/208 where the master branch now depends on CLI 1.0.1.  The CLI 1.0.0 development was moved to the sdk-1.0.0 of the nightly repo therefore the CLI 1.0.0 subscription needed to be tweaked accordingly.
> Add subscription for Docker to update CLI 1.0.1 dependency

- Maestro/subscriptions.json
Recently added subscription was making the PRs against master when they should be on the sdk-1.0.0 branch.
> Set GITHUB_UPSTREAM_BRANCH for Docker sdk-1.0.0 subscription

- Maestro/subscriptions.json
I cloned an executor definition in DevDiv and set it up for Core-Setup. With this change, all triggered builds exist on DevDiv.
Core-Setup auto-updates should flow after this, but I'll run a dotnet/standard build (<10 min build time) and look closely at the results to make sure.
/cc @ericstj @gkhanna79 @dleeapho
> Move Core-Setup executor from MSEng to DevDiv

- build-info/dotnet/corefx/master/Latest_Packages.txt
I noticed some packages weren't updated in https://github.com/dotnet/versions/commit/ca917e7e2e1db8d17e279c045758a1abc62a7210#diff-b64b0edcf4b46fafc86baec415ff9201, indicating that CoreFX no longer builds them. Servicing is the reason to leave packages from old builds in the file, and this is a master build where that doesn't apply.
Is it useful to be able to see when packages stop being produced, @weshaggard, or should master branch builds always remove these old entries?
> Prune packages no longer produced in corefx/master

- Maestro/subscriptions.json
This reverts commit c3841e616a165c24f2e0b74a4486bb83cbd435f0. (https://github.com/dotnet/versions/pull/125)
@gkhanna79 @wtgodbe
> Enable per-PR builds of Core-Setup 1.1.0/1.0.0

- Maestro/subscriptions.json
- Making use of the CLI_RELEASE_PREFIX added with https://github.com/dotnet/dotnet-docker-nightly/pull/226.
- Cleaning up obsolete sdk-1.0.0 subscription.
> Update Docker subscriptions for cli 2.0.0

- Maestro/subscriptions.json
* Since WCF cannot move to the latest buildtools until other issues are resolved the PRs being generated cannot be merged and will always fail CI tests.
> Removing WCF from the automatic PRs for version updates.

- Maestro/subscriptions.json
This will avoid build failure noise until it's working again.
Fix is tracked by https://github.com/dotnet/core-setup/issues/2208--then we can revert this and make whatever changes are needed.
/cc @karajas @eerhardt @weshaggard
> Temporarily disable core-setup/master auto-update

- Maestro/subscriptions.json
The core-setup-general definition defaults to release/1.0.0, so master must be specified.
I didn't think of this when reviewing https://github.com/dotnet/versions/pull/153.
/cc @karajas @chcosta @weshaggard
> Set core-setup master auto-update branch

- Maestro/subscriptions.json
@dotnet/core-setup-contrib 
For CoreCLR there are separate `dotnet/coreclr-contrib` and `dotnet/coreclr-auto-update-notify` groups. We could do that for core-setup as well. Let me know and I can create a `dotnet/core-setup-auto-update-notify` team.
> Notify dotnet/core-setup-contrib on master auto-PR

- Maestro/subscriptions.json
This reverts commit 447f6edaa62fdad75bcc785979e4990651197fc7. (https://github.com/dotnet/versions/pull/144)
Core-Setup 1.1.0 and 1.0.0 servicing branches are ready for new builds.
/cc @gkhanna79 @weshaggard @eerhardt @leecow @wtgodbe
> Revert "Disable CI triggers for core-setup 1.0.0 and 1.1.0"

- Maestro/subscriptions.json
Since Core-Setup master was merged into release/2.0.0, the auto-update call needs to be changed to match the BuildTools bringup that happened in master. `build_projects\update-dependencies\update-dependencies.ps1` no longer exists.
I copied the subscription from Core-Setup master to release/2.0.0 and changed the branch.
> Fix Core-Setup release/2.0.0 auto-update trigger

- Maestro/NuGet.Config
CI has sometimes been unable to restore packages because it is only looking at local sources. Add a NuGet.Config file to make sure we can acquire the packages, no matter what the machine state is.
See https://github.com/dotnet/versions/pull/157, https://github.com/dotnet/versions/pull/158
> Add a NuGet.Config to ensure nuget.org feed used

- build-info/dotnet/cli/release/2.0.0/Last_Build_Packages.txt
- build-info/dotnet/cli/release/2.0.0/Latest.txt
- build-info/dotnet/cli/release/2.0.0/Latest_Packages.txt
Automatic updates of CLI are currently paused, waiting on https://github.com/dotnet/buildtools/pull/1556.
This updates the CLI info for dotnet-CLI to the last known good build of dotnet/cli/release/2.0.0
cc @dagood @livarcocc
> Updating build-info/dotnet/cli/release/2.0.0 for preview2-006467

- Maestro/subscriptions.json
Seed subscriptions for the release/uwp6.0 branches of coreclr, corefx and core-setup.  If there are additional triggers or files that should be monitored, the product team should now feel empowered to add them.
> Add subscriptions for UWP 6.0

- Maestro/subscriptions.json
Please review the trigger paths, comparing to CoreFx's triggers, should I have 'standard' and 'core-setup'?
> Add maestro subscription for WCF release/uwp6.0

- Maestro/subscriptions.json
This new subscription will trigger official builds of the dotnet-docker repo whenever an image it depends on changes.
> Add subscription to trigger dotnet-docker build on base image change

- Maestro/src/Microsoft.DotNet.Maestro.WebApi/Models/ModifiedFileModel.cs
- Maestro/src/Microsoft.DotNet.Maestro.WebApi/Models/SubscriptionsModel.cs
- Maestro/src/Microsoft.DotNet.Maestro.WebApi/Services/HandlerResolver.cs
- Maestro/src/Microsoft.DotNet.Maestro/Handlers/VsoBuildHandler.cs
- Maestro/src/Microsoft.DotNet.Maestro/Services/VsoParameterGenerator.cs
PTAL @eerhardt @dagood 
This will add some well known arguments `<trigger-repo>`, etc to get information about what triggered the run. I brought this together yesterday while it was top of mind but I will likely finish it after the current servicing releases.
> Add support for passing trigger information to the handlers

- Maestro/subscriptions.json
Accidentally pointed the triggers as the versions repo when it
should be pointed at the individual source repos.
cc @eerhardt @safern
> Update to trigger paths to the corefx/coreclr repos

- build-info/dotnet/wcf/release/1.0.0/LKG_Packages.txt
In order to build 1.0.0 in VSO buildtools expects an LKG file during the sync step. I assume it pulls down these versions of the WCF packages for build purposes. I haven't gotten there yet but I expect that tests will run against the "just built" packages.
> Need LKG file to build 1.0.0 branch in VSO.

- Maestro/subscriptions.json
This was the source of the following build failure - https://devdiv.visualstudio.com/DevDiv/_build?tracking_data=eyJTb3VyY2UiOiJFbWFpbCIsIlR5cGUiOiJOb3RpZmljYXRpb24iLCJTSUQiOiI1ODI2NCIsIlNUeXBlIjoiUEVSIiwiUmVjaXAiOjEsIl94Y2kiOnsiTklEIjoxNTUwMjEyMiwiTVJlY2lwIjoibTA9MSAiLCJBY3QiOiI2NTJjZjMwNS02ODMyLTRkMTAtYWJlMC1kMTczZGVhNTA5YzUiLCJmZiI6IkNEIn19&buildId=1089929
Related to this change I logged https://github.com/dotnet/dotnet-docker-nightly/issues/476
> Update Docker subscription to pickup latest cli 2.2

- Maestro/src/Microsoft.DotNet.Maestro.WebApi/Controllers/CommitPushedController.cs
- Maestro/src/Microsoft.DotNet.Maestro.WebApi/Models/Commit.cs
- Maestro/src/Microsoft.DotNet.Maestro.WebApi/Models/ModifiedFileModel.cs
- Maestro/src/Microsoft.DotNet.Maestro.WebApi/Models/SubscriptionsModel.cs
https://github.com/dotnet/versions/issues/205
Builds on the substitution feature added in https://github.com/dotnet/versions/pull/187
I see `id` defined in real webhook payloads, and also defined here: https://developer.github.com/v3/activity/events/types/#webhook-payload-example-26
> Add a parameter substitution for commit id

- Maestro/subscriptions.json
These operations share a common Executor def that provides config and secrets.
Example publishes to testing locations:
* Packages: https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=1285064
* Blobs: https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=1285013
> Create trigger for orchestrated build final package and blob publish

- Maestro/subscriptions.json
cc @mmitche @dagood 
Corefx is the only one that uses this trigger type for the mirror. We should enable this for all the repo's and create one common mirror definition and pass the repo and branch.
> Update CoreFx mirror triggers to mirror all release branches

- Maestro/subscriptions.json
cc @mmitche @dagood 
I've created a general purpose VSTS build definition for mirroring changes. I will test it out on corefx and once it appears to be working OK I will switch others to using it as well.
> Switch to a general purpose vsts to github mirror build definition

- Maestro/subscriptions.json
Right now this is parallel to publish steps: the bits will publish, regardless of signing issues. We can change this in the future (once we at least are confident in the whitelist) so that publish triggers on the validation success semaphore.
https://github.com/dotnet/core-eng/issues/2434
> Create triggers for post-build signing validation

- Maestro/subscriptions.json
cc @dagood @safern 
Trying to figure out why the branch information wasn't correctly being passed to the mirror I finally figured out we didn't actually pass them as vsobuildparameters. This should fix that.
> Fix parameters to actually be vsoBuildParameters

- Maestro/subscriptions.json
c @mmitche @dagood 
This is a follow-up to move to all the core repos to one general definition for mirroring. 
Also removed some defaultinf subs which are no longer needed as the branch is deleted at this point.
> Add coreclr and core-setup github-vsts triggers

- Maestro/subscriptions.json
Remove dependency update for core-setup release/uwp6.0 build. Also remove triggers that track core-setup release/uwp6.0 and projectn-tfs release/uwp6.0.
> Update release/uwp6.0 triggers

- build-info/dotnet/product/cli/release/2.1/README.md
* Add ASP.NET Core Runtime section.
* Fix Core-Setup links. Remove not-yet-available checksum links (https://github.com/dotnet/core-eng/issues/2437) and use distro-agnostic artifacts.
I've already changed the generation process to create the readme like this in the future. I figure reviewing this is a good idea anyway, to make sure it will have what everyone needs.
@natemcmaster @wli3 @johnbeisner PTAL
cc @weshaggard @shawnro
> Fix release/2.1 cli product build README

- Maestro/subscriptions.json
Adding a trigger to automatically update the master CLI branch when roslyn 15.7 changes.
cc @eerhardt
> Adding a trigger to automatically update the master CLI branch

- Maestro/subscriptions.json
Moves publish away from the `-test` locations.
We shouldn't merge this until we know the manifests are ok and won't overwrite blobs built by `master`. aspnet requires some build-to-build overwriting because it includes its "latest" files in the manifest, so we can't just disable overwrites.
> Point release/2.1 publish at real locations

- Maestro/subscriptions.json
Start copying 2.1 Core-Setup and CLI builds to the `release/2.1` channel. This gives us the stable links on `dotnetcli`/`dotnetclichecksums` that are used in the Core-Setup and CLI repo readmes. (Those readmes aren't suitable to auto-upgrade, unlike the readme on dotnet/versions.)
> Enable Copy to Latest for 2.1

- Maestro/subscriptions.json
1. Update the Docker update dependencies trigger to make use of the new packages+installers semaphore.
2. Add back the Docker source build parameters which I recently removed.  I thought these weren't going to be required but pipebuild requires them.
> Misc Docker subscription updates

- Maestro/subscriptions.json
Also add in vsoSourceBranch for master branches: avoid future copy-paste errors and make CoreCLR and CoreFX consistent with Core-Setup's subscription.
Fixes up https://github.com/dotnet/versions/pull/232, which added the new subscriptions.
https://github.com/dotnet/core-eng/issues/2435
The Core-Setup update PR was generated (https://github.com/dotnet/core-setup/pull/3705), but none for CoreFX/CoreCLR.
> Add missing vsoSourceBranch args for release/2.1

- Maestro/subscriptions.json
Fix the CLI latest channel to match the built branch so the CLI repo's readme works.
> Copy prodcon 2.1 CLI to release/2.1.3xx channel

- Maestro/subscriptions.json
This reverts commit ff3c67ee606dad7c3ac932195916fb1add00e3eb.
The publish steps have started running, and to be safe I'd like to turn off the triggers in case there's an inadvertent change later.
> Revert "Add subscriptions for 2.1-preview1 publish"

- Maestro/subscriptions.json
Arcade is still a private repo for the moment,  I needed to clone the mirror definition to handle an authenticated GitHub url clone.  
/cc @dagood @weshaggard
> Use mirror which can handle private repos

- Maestro/subscriptions.json
Uses new script added in https://github.com/dotnet/coreclr/pull/16868.
@wtgodbe, do you think you can port this to CoreFX release/1.1.0, and the other fix to CoreFX release/1.0.0? (No dotnet/versions change needed for the 1.0.0 one.)
> Use UpdateDependencies.ps1 for CoreCLR 1.1.x

- Maestro/subscriptions.json
I've updated the mirror def to support private repo's. This is the corresponding change to switch the repo's over to the shared mirror.
@eerhardt @weshaggard @dagood
> Move private repo's to standard mirror

- Maestro/subscriptions.json
This is the only place `dotnet-bot` is used in a subscription. Moving to the preferred `dotnet-maestro-bot` account lets us simplify the definitions and reduce the permissions that auto-PR generation code has access to.
The only visible change will be that WCF release/2.0.0 auto-PRs start coming from @dotnet-maestro-bot, like they do for the other WCF branches already.
Related to https://github.com/dotnet/core-eng/issues/2382
FYI @StephenBonikowsky
> Switch WCF release/2.0.0 to use dotnet-maestro-bot

- Maestro/subscriptions.json
The WCF branch 2.0.0 does not use buildtools v2 so using the workaround that was used for 1.1.0 regarding the TLS 1.2 requirement.
Related to dotnet/wcf#2676
> Have the subscription for WCF 2.0.0 use the new UpdateDep script.

- build-info/dotnet/projectn-tfs-ilc/master/Latest.txt
- build-info/dotnet/projectn-tfs-ilc/master/Latest_Packages.txt
Issues during package publish caused a torn set of packages in the versions repo. Fix up the packages so we have the right set versioned consistently.
> Fix missing ProjectN ILC packages

- Maestro/subscriptions.json
A subscription to submit an auto-update PR to source-build whenever a 2.1 ProdCon build finishes. The PR updates the submodules based on the commits in the orchestrated build manifest. [New source-build-general VSTS def](https://devdiv.visualstudio.com/DevDiv/Default/_build/index?context=allDefinitions&path=\DotNet\Maestro&definitionId=8760&_a=completed).
Waiting for https://github.com/dotnet/source-build/pull/371 to add the prodcon submodule updaters to source-build.
https://github.com/dotnet/source-build/issues/342
> Update source-build from ProdCon 2.1 builds

- Maestro/subscriptions.json
source-build's build.cmd sets "/clp:v=m", so we need to set "/clp:v=" as well, rather than "/v:".
This makes it so you can see what's happening in Maestro-Source-Build-GeneralExecutor, like the link to the PR that's created.
/cc @crummel @dseefeld
> Properly set source-build update verbosity

- Maestro/subscriptions.json
Nightly builds of aspnetcore images are now in dotnet/dotnet-docker, so we don't need maestro to run on aspnet/aspnet-docker anymore.
@MichaelSimons @dagood
> Remove triggers for aspnet-docker

- Maestro/subscriptions.json
This should allow aspnetcore to take new dependencies when core-setup passes instead of waiting for final ProdCon. It depends on aspnet/Universe#1011.
> Update aspnetcore from core-setup

- Maestro/subscriptions.json
Set up triggers that will run 2.1-rc1 publish. Extended symbol expiration date.
> Add subscriptions for 2.1-rc1 publish

- Maestro/subscriptions.json
This branch was renamed to match other dotnet repos, and auto-updates need to be pointed there.
/cc @dleeapho @crummel @dseefeld
> Update source-build dev/release/2.1 to release/2.1

- Maestro/subscriptions.json
The dotnet-docker-nightly-pipebuild build definition was recently replaced with dotnet-docker-nightly as part of https://github.com/dotnet/dotnet-docker/pull/553.
> Update dotnet-docker-nightly build definition reference

- Maestro/subscriptions.json
The dotnet instance appears a little less forgiving, or at least this appears to be related to the error
> Make source branch for queued build explicit

- build-info/dotnet/standard/release/2.0.0/Last_Build_Packages.txt
- build-info/dotnet/standard/release/2.0.0/Latest.txt
- build-info/dotnet/standard/release/2.0.0/Latest_Packages.txt
This reverts commit 7ff3a32a8b6986fe295ff3a8d9f83bc9d399b3ae.
Undo'ing this to move back to the 2.0.3 stable version as we aren't
ready for any newer version of this package yet.
FYI @wtgodbe @mmitche
> Revert "Updating build-info/dotnet/standard/release/2.0.0 for servicing-26522-02"

- Maestro/subscriptions.json
There was a source-build-specific mirror build definition that was only mirroring `master`--I've disabled that.
> Mirror source-build GitHub to devdiv VSTS

- Maestro/subscriptions.json
The Core repos list each release branch to exclude the 2.1 one. `release/**/*` is good for source-build (for now).
Example manual trigger: https://devdiv.visualstudio.com/DevDiv/Default/_build/results?buildId=1775772
> Merge source-build changes across VSTS branches

- Maestro/subscriptions.json
- Updates to base image dependencies (alpine 3.7, alpine edge, and buster)
- Removed samples build hook as builds now are based on VSTS yml which provide this functionality
- Updated dotnet-docker build definition reference.  This changed as a result to moving to yml based builds.
> Update docker build reference and docker base image dependencies

- Maestro/subscriptions.json
We construct the fullpath https://github.com/dotnet/versions/blob/482b2c2718d3e9d75da3f944f459f0863c315ebb/Maestro/src/Microsoft.DotNet.Maestro.WebApi/Models/ModifiedFileModel.cs#L49 here to match with triggerPaths
we use blob rather than tree while constructing the build path.
cc @safern @dagood
> Correcting the Trigger Paths for the new subscriptions

- Maestro/subscriptions.json
The latest maestro PR to aspnet attempted to move aspnet ahead from 2.2 to 3.0. On aspnet, our dev branches are still appointed for 2.2 work (for now), so I'm updating the maestro trigger to only run for 2.2 changes.
@weshaggard do you have plans to enable publishing for the release/2.2 branches? I don't actually see anything for 2.2 under https://github.com/dotnet/versions/tree/master/build-info/dotnet/core-setup/release.
> Align 2.2 branches between aspnet and core-setup

- Maestro/subscriptions.json
cc @dagood @natemcmaster 
Fix the trigger paths for the subs I setup in https://github.com/dotnet/versions/pull/329.
> Fix trigger paths for 2.1->2.2 mirror

- Maestro/subscriptions.json
This should enable maestro insertions of .NET Core runtime components into dotnet/core-sdk.
@natemcmaster @mmitche This doesn't currently cover ASP.NET.  What would we need to add to this to get ASP.NET updates via maestro?  I see this for the 2.2.1xx branch:
```json
{
"triggerPaths": [
"https://github.com/dotnet/versions/blob/master/build-info/dotnet/product/cli/release/2.2/packages.semaphore",
],
"action": "cli-dependencies",
"delay": "00:05:00",
"actionArguments": {
"vsoSourceBranch": "release/2.2.1xx",
"vsoBuildParameters": {
"GITHUB_PULL_REQUEST_NOTIFICATIONS": "dotnet/dotnet-cli",
"GITHUB_UPSTREAM_BRANCH": "release/2.2.1xx",
// Enable once this is done https://github.com/aspnet/Universe/issues/1013.
// "ASPNET_VERSION_FRAGMENT": "<version fragment>",
"SDK_VERSION_FRAGMENT": …
```
> Set up maestro insertions for dotnet/core-sdk

- Maestro/subscriptions.json
* We prefer not to update our CoreFx dependency in servicing branches unless specifically desired or required.
* Our Master branch is comparable to the CoreFx release/2.2 branch for now for purposes of dependencies and auto-updates.
> Updating WCF subscriptions.

- Maestro/subscriptions.json
2.1 => 2.2 => master
This reduces the manual porting work to get a change in all branches.
There are some conflicts right now for merging 2.2 into master... let me know if I should just skip that one.
> Add dotnet/buildtools auto branch merge PRs

- Maestro/subscriptions.json
To get an initial publish of the symbols for 2.1.5 validation.
> Add symbol/signing validation check for 2.1.5

- Maestro/subscriptions.json
Since we have split out the IBC training from the PGO training we need
to monitor both locations for updates. This will track with
https://github.com/dotnet/optimization/pull/139 as that is the change to
how we write out the tracking files for the optimization repo.
> Update trigger paths for optimization repo

- Maestro/subscriptions.json
> Adding clicommandlineparser and cli-migrate to dnceng mirroring

- Maestro/subscriptions.json
Since we are not currently updating the IBC package and there is nothing
in the location this is causing a crash in the maestro job. I am going
to remove this until we have the data pushing then we can add this back.
> Remove IBC update line

- Maestro/subscriptions.json
I removed this as we were not producing IBC pacakges at the time, but
now that we have IBC data being regularly updated we should switch this
trigger back on.
> Add tracking for IBC package

- Maestro/subscriptions.json
cc @dagood @MattGal @mmitche 
I created a wrapper update-dependencies script in corefx to deal with the build changes caused by the move to arcade. see https://github.com/dotnet/corefx/pull/32896
> Switch to new eng/update-dependencies.cmd script to update dependencies

- Maestro/subscriptions.json
The dotnet-docker-general build id changed because the build definition moved to yaml.
> Update the dotnet-docker-general build id

- Maestro/subscriptions.json
This is to support building Microsoft/clrmd (https://www.nuget.org/packages/Microsoft.Diagnostics.Runtime) in dev.azure.com/dnceng
FYI @leculver - this will be mirroring the `master` branch, as well as any branch that starts `release/` to the internal AzDO tenant (will send an email with a few more details). We'll drive the official build off the mirrored commits.
cc @pakrym @davidfowl
> Add Microsoft/clrmd to source mirroring

- build-info/dotnet/product/cli/release/2.2.0/build.xml
As discussed with @muratg @blowdart @Tratcher
> Manually set Microsoft.Owin.Security.Interop to not ship in 2.2.0

- Maestro/subscriptions.json
Please hold off on merging until we confirm what branching will look like for Standard/Buildtools (CC @danmosemsft @leecow - are we planning on branching buildtools to 3.0 as well?)
@dagood @mmitche PTAL
@livarcocc is the versioning correct for the CLI dependency?
> Add auto-update for CoreFx 3.0

- Maestro/subscriptions.json
These branches don't exist yet, but once we create them, this will make sure any changes made to release/3.0-preview3 flow back into master (if there are any...we hope this branch will have a short life)
cc @dougbu @eilon @mmitche
> Enable bot PRs to flow release/3.0-preview3 branches back into master for aspnet

- Maestro/subscriptions.json
Remove PGO, IBC, CoreFX, and Core-Setup flow to CoreCLR as the now flow using Darc/Maestro++
> Remove PGO, IBC, CoreFX, and Core-Setup flow to CoreCLR

- Maestro/subscriptions.json
Please don't merge this until the release/3.0 branches are open for Preview4 (I'll poke at this PR once that's the case)
Adds auto-merges from master into release/3.0 for CoreClr, CoreFx, and Core-Setup.
@mmitche @dagood PTAL
CC @danmosemsft
> Add auto-merge from Master into Release/3.0

- Maestro/subscriptions.json
I've just branched buildtools to release/3.0 (as per discussions on Friday), so we should update Core* dependencies from there rather than from master. https://github.com/dotnet/buildtools/commit/2912fd36eaffe4e998073044d0be9319ff5213dd
CC @danmosemsft @leecow @mmitche @dagood
> Update Core* repos from buildtools 3.0 rather than master

- Maestro/subscriptions.json
This is the trigger to rebuild the dotnet-docker repos whenever a base image is changed.  Right now, two builds are getting triggered at the same time - master and nightly.  They are both fighting for the same machines.  The master branch should be given priority.
cc @mthalman
> Add dotnet-docker nightly build trigger delay to prioritize master builds 

- Maestro/subscriptions.json
We use this repo for some infrastructure tools we currently run through TeamCity and want to start using AzDO for this. We need to mirror to dnceng/internal so that we can use it there :)
cc @Eilon @jkotalik @dougbu @ryanbrandenburg
> Mirror aspnet/AspNetCore-Internal

- Maestro/subscriptions.json
`Microsoft/visualfsharp` was recently renamed to `dotnet/fsharp`.
@mmitche for review.
> add subscription for dotnet/fsharp

- Maestro/subscriptions.json
F# needs to mirror `feature/*` branches.
@mmitche for review.
> update subscriptions for dotnet/fsharp

- Maestro/subscriptions.json
This is being replaced by our own system for managing base images.  See https://github.com/dotnet/docker-tools/issues/59
> Remove subscription for dotnet-docker/nightly

- Maestro/subscriptions.json
Corert does not have any release branches so removing them from the list of subscriptions
> Adding 3.0 to list of subscriptions in order to mirror these branches

- build-info/docker/image-info.dotnet-dotnet-docker-nightly.json
This just copies the image info file content related to the dotnet-docker repos' nightly branch into its own file.  This is related to https://github.com/dotnet/dotnet-docker/pull/1262.
> Split image info file for dotnet-docker nightly

- build-info/docker/image-info.dotnet-dotnet-buildtools-prereqs-docker-master.json
This just copies the image info file content related to the dotnet-buildtools-prereqs-docker repo's master branch into its own file.  This is related to https://github.com/dotnet/dotnet-docker/pull/1262.
@MichaelSimons
> Split image info file for buildtools-prereqs

- Maestro/subscriptions.json
Remove the automatic build trigger for the dotnet-docker repo when base image changes occur.
> Remove base image pipeline trigger for dotnet-docker

- Maestro/subscriptions.json
Adding rules for automatically porting WPF changes from...
- ... release/3.0 -> release/3.1
- ... release/3.1 -> master 
/cc @mmitche, @rladuca
> Add rules for WPF branches

- build-info/docker/image-info.Microsoft-dotnet-framework-docker-master.json
- build-info/docker/image-info.dotnet-dotnet-buildtools-prereqs-docker-master.json
- build-info/docker/image-info.dotnet-dotnet-docker-master.json
- build-info/docker/image-info.dotnet-dotnet-docker-nightly.json
- build-info/docker/image-info.json
The new format for image info files that is rolling out will explicitly have the Dockerfile name included for the image's key value.  This updates the existing image info files so they are compatible.
See https://github.com/dotnet/docker-tools/pull/302
> Update image info format to include Dockerfile name

- Maestro/subscriptions.json
CC @mmitche @dougbu @Anipik 
Will revert this once the 3.1-preview1 builds are done. Incidentally, does anyone know how the merge PRs into core-SDK & friends are created? e.g. https://github.com/dotnet/toolset/pull/2875. These go through dotnet-bot, rather than dotnet-maestro-bot.
> Disable auto-merges into release/3.1 branches while coherent builds are running

- Maestro/subscriptions.json
Reverts dotnet/versions#513
Re-enables merge PRs for the dotnet repos into release/3.1. I'll merge this once builds for 3.1-preview1 are done.
CC @Anipik
> [NO MERGE] Revert "Disable auto-merges into release/3.1 branches while coherent builds are running"

- Maestro/subscriptions.json
Disable auto-merges from 3.0 -> 3.1 while 3.1 is in lockdown for preview2.
CC @mmitche @Anipik
> Disable auto-merges during 3.1-preview2 lockdown

- Maestro/subscriptions.json
CC @Anipik @livarcocc @nguerrera @dagood @dougbu 
I'll merge this Sunday, then revert it after we declare a final build for GA
> Disable 3.0 -> 3.1 auto-merges during Preview3 build window

- Maestro/subscriptions.json
- Remove 3.0 -> master merge.  Master will likely diverge quite a bit from 3.0, and replacing it with a 3.1 -> master merge doesn't seem any better.
- Remove 2.1 -> 2.2 merge.  The only updates being made in 2.x are Version.Details.xml changes, which we never want to mirror anyway.
> Update source-build subscriptions.

- Maestro/subscriptions.json
Adding repo https://github.com/aspnet/SignalR-Client-Cpp to the repo syncing (to sync the repo to AzDO).
This repo is for the ASP.NET Core SignalR C++ Client, which doesn't actually ship binaries (the repo is the only actual "shipping" vehicle since every consumer builds the repo from source). However, we still want to do the internal mirroring for "official" validation builds (even though they don't produce artifacts) and archival/continuity purposes.
The intention is to set up the triggers to:
* Mirror `master` and `release/*` branches to AzDO repo aspnet-SignalR-Client-Cpp
* Mirror `release/*` branches to `internal/release/*` branches in the same AzDO repo.
I'd appreciate someone who knows Maestro confirming that I did the right JSON to do those things ;P.
> add SignalR C++ client to repo sync jobs

- Maestro/subscriptions.json
We are no longer want any functional fixes so switching of the autmatic prs opening.
This should also prevent any accidental merges of functional fixes
> Disable automatic opening of prs into 2.2 branch

- build-info/docker/image-info.dotnet-dotnet-docker-master.json
Official .NET Docker build didn't update the image info file for some Alpine runtime-deps images.  Manually updating them to the correct values.
> Update base digest values of .NET Alpine Docker images

- build-info/docker/image-info.dotnet-dotnet-buildtools-prereqs-docker-master.json
Manually updating image info data for the https://github.com/dotnet/dotnet-buildtools-prereqs-docker repo because there was infrastructure issues in having that done automatically.  Also removes some obsolete data for out of support images.
> Update build tools prereqs image info

- Maestro/subscriptions.json
- going through 'blazor-wasm' branch is complicating things
nit:
- update syntax for 'release/2.1' matches
> Merge aspnetcore 3.1 -> master

- Maestro/subscriptions.json
Added triggers for MSBuild `vs16.*` branches to get pull requests created from `vs16.*` -> `master`. 
Explanation from @dagood 
> What's going on is that `/**/*` means it matches file changes where the url starts with everything up to the `/`, exclusive.  So `...blob/vs16./**/*` will do what you want. The double-slashes are to make sure this doesn't happen.  It's weird. https://github.com/dotnet/versions/blob/1c00f953854d79e4b2ee368495c58de6b39d8e79/Maestro/src/Microsoft.DotNet.Maestro.WebApi/Models/SubscriptionsModel.cs#L89
Related issue with a detailed explanation: https://github.com/dotnet/versions/issues/558
> Adding MSBuild vs16.x branches to automate PRs into master

- Maestro/subscriptions.json
F# doesn't need internal signed builds from any `feature/*` branches, so the mirror can be turned off.
> remove F# feature merges

- Maestro/subscriptions.json
https://github.com/dotnet/versions/pull/564 disabled this merge, but https://github.com/dotnet/versions/pull/563 was merged afterwards and touched a neighboring section of the code, so it got put back in during the merge conflict resolution. Re-disabling it here.
CC @mmitche @wli3 @dotnet/aspnet-build
> Re-disable merges from aspnetcore rel/3.1 -> blazor-wasm

- Maestro/subscriptions.json
Adds dotnet/tye to the mirroring process.
I could use a double-check from anyone who's familiar with the process, because this is my first time doing this 😁. I don't need any automated merges.
> Add dotnet/tye to mirroring job

- build-info/docker/image-info.dotnet-dotnet-docker-master.json
Reverting the update that was made by the samples build because it wiped out the product image info data.
This reverts commit a244d0b82796bc445107bd8446ad0242600f935e.
> Revert "Merging image info updates from build."

- build-info/docker/image-info.Microsoft-dotnet-framework-docker-master.json
- build-info/docker/image-info.dotnet-dotnet-buildtools-prereqs-docker-master.json
- build-info/docker/image-info.dotnet-dotnet-docker-master.json
The image info files are getting corrupted by builds that only build a partial set of the images that are represented within the image info file.  The publish of the image info ends up clearing out anything that wasn't part of the build.  I've reverted the changes to these files back to their original state and then manually added back the content for the new images that were recently published.
Related: https://github.com/dotnet/docker-tools/pull/475
> Fix up image infos that got corrupted

- build-info/docker/image-info.dotnet-dotnet-docker-master.json
After the https://github.com/dotnet/versions/blob/master/build-info/docker/image-info.dotnet-dotnet-docker-master.json file got corrupted yesterday, I had attempted to restore and update it with current content in https://github.com/dotnet/versions/pull/588.  But in those changes, I didn't correctly update the content for the sample images.  This is causing the base image checking system to think the samples need to get rebuilt when they do not need to be.  These changes fix up the content so that things are up-to-date with the actual images that are currently published.
> Fixing up samples image info

- Maestro/subscriptions.json
Pretty self-explanatory. Repo is public and the internal mirror repo already exists.
> Add AzDo sync for microsoft/reverse-proxy

- build-info/docker/image-info.dotnet-docker-tools-master.json
Adds a placeholder file so that builds can successfully resolve an image info file for the docker-tools repo in order to validate the "publish image info" task.
Related: https://github.com/dotnet/docker-tools/issues/474
> Add placeholder image info for docker-tools

- Maestro/subscriptions.json
We have a new repo `dotnet/insertions-client` that needs to be mirrored into dnceng/internal
> Add dotnet/insertions-client for mirroring

- Maestro/subscriptions.json
For https://github.com/dotnet/source-build/issues/1634
> Fix SBRP release branch repo mirror: typo

- Maestro/subscriptions.json
Also added `exp/*` to devdiv mirror so we can continue to use the experimental-branch-to-official-build-to-VS-insertion-PR flow.
@MattGal
> Move MSBuild to its new dotnet home

- Maestro/subscriptions.json
Accounting for the microsoft->dotnet org move.
@MattGal I missed this one, sorry.
cc @BenVillalobos
> Fix MSBuild release-branch RI automation

- Maestro/subscriptions.json
Merges aspnetcore/efcore release/5.0 branches to release/5.0-rc2, and release/5.0-rc2 to master. Once we finish rc2 builds, this should be undone
> Add policies for aspnet rc2 branches

- Maestro/subscriptions.json
- also correct efcore-related automation to use 'main' branch where appropriate
> Flow ASP.NET `release/5.0-rc2` into `release/5.0`

- build-info/docker/image-info.dotnet-docker-tools-master-imagebuilder.json
- build-info/docker/image-info.dotnet-dotnet-buildtools-prereqs-docker-master.json
- build-info/docker/image-info.dotnet-dotnet-docker-master-samples.json
- build-info/docker/image-info.dotnet-dotnet-docker-master.json
- build-info/docker/image-info.dotnet-dotnet-docker-nightly.json
- build-info/docker/image-info.microsoft-dotnet-framework-docker-master-samples.json
- build-info/docker/image-info.microsoft-dotnet-framework-docker-master.json
The format of the `osVersion` field was changed by https://github.com/dotnet/docker-tools/pull/697
> Convert Docker image info files to new osVersion format

- build-info/docker/image-info.dotnet-docker-tools-master-imagebuilder.json
- build-info/docker/image-info.dotnet-dotnet-buildtools-prereqs-docker-master.json
- build-info/docker/image-info.dotnet-dotnet-docker-master-samples.json
- build-info/docker/image-info.dotnet-dotnet-docker-master.json
- build-info/docker/image-info.dotnet-dotnet-docker-nightly.json
This is a continuation of the changes from https://github.com/dotnet/versions/pull/651.  I missed converting the Linux-based OS version values.
> Update format of osVersion in image info files

- build-info/docker/image-info.dotnet-dotnet-docker-master.json
- build-info/docker/image-info.dotnet-dotnet-docker-nightly.json
Fixing `osVersion` for Dockerfiles based on stretch-slim to use `stretch-slim` instead of `stretch`.
> Fix osVersion in Docker image info files

- Maestro/subscriptions.json
Ref. https://github.com/mono/linker/issues/1775
> Rename Maestro sub for mono/linker for master->main

- Maestro/subscriptions.json
Once 5.0.2xx reached servicing. It will get the latest runtime.
And that is not what we want in master. While 5.0.3xx is the branch with active
development
> Change auto merge from 5.0.2xx to 5.0.3xx

- Maestro/subscriptions.json
**Part of March's batched infrastructure rollout: https://github.com/dotnet/runtime/issues/48168**
@dotnet/dnceng
> Master to main renaming for dotnet/runtime

- Maestro/subscriptions.json
Changing branch to main for test-templates
Part of this work [Renaming default branch to main for test-tempates](https://github.com/dotnet/test-templates/issues/131).
> Changing branch to main for test-templates

- Maestro/subscriptions.json
Note: `/**/*` in this file means `.*$`, not `/.*$`, so counterintuitively, the release branch pattern should work. (See https://github.com/dotnet/versions/issues/558.)
> Mirror new repository

- Maestro/subscriptions.json
This is part of WPF's default branch change to main.  Thanks.
> Change WPF 'master' to 'main' in subscriptions.json

- Maestro/subscriptions.json
we are archiving the extensions repo which means there will  no longer a master branch, hence deleting all the subscripitions.
cc @wtgodbe @eerhardt
> Remove the subscriptions on the extensions master branch

- Maestro/subscriptions.json
Update `subscriptions.json` to migrate `dotnet/spark` to `main`.
> Update subscriptions.json to migrate dotnet/spark to main

- Maestro/subscriptions.json
- in midst of renaming default branch of dotnet/aspnetcore-tooling
- ef6 'master' branch no longer exists, should not be target of merge PRs
- aspnet/aspnetcore-internal doesn't have an internal mirror
> Handle more master to maining

- Maestro/subscriptions.json
These have also been failing in the pipeline because the repos renamed their base branch. This should fix this for
* sdk
* installer
* wpf
> Fix a couple more github-dnceng-branch-merge-pr-generator subscriptions

- Maestro/subscriptions.json
Also ensure any vs* branch update gets a PR generated from it instead of just 16.*
> Update msbuild's trigger to point to main

- Maestro/subscriptions.json
- for some reason, @mmitche claims this isn't a microformat 😀
> Handle all `release/6.0*` branches

- Maestro/subscriptions.json
Disabled 17.0 PR's flowing into main by starting the glob after `vs16`
/cc: @rainersigwald https://github.com/dotnet/msbuild/pull/6353
> Disable msbuild/vs17.0 PR's into msbuild/main

- Maestro/subscriptions.json
We renamed main to make it less confusing as the purpose of that branch is for documentation reasons. However we have a yml file that we want to be mirrored into internal repo as we use it as the mirror from dotnet/runtime to dotnet/runtimelab. 
cc: @ViktorHofer @mmitche
> Update runtimelab default branch in triggers

- Maestro/subscriptions.json
MSBuild has two Dev16 release branches with non-trivial development activity. We want changes to both to roll forward to `main`, and additionally we want `16.10` to roll forward to `16.11`.
> Update Maestro auto-PR rules for MSBuild 16.10 and 16.11

- Maestro/subscriptions.json
- This transitions the pre-existing release/vs17.0-pp1 to main-vs-deps.
/cc @dougbu
> Auto-merging main -> main-vs-deps for aspnetcore-tooling.

- Maestro/subscriptions.json
I left EF alone for now - @ajcvickers please let me know if you'd like me to get rid of the inter-branch merges for EF as well.
> Remove interbranch merges for asp.net

- Maestro/subscriptions.json
This is what our release branches will likely be so setting up the automatic RI.
> MSBuild: automerges for vs17*->main

- Maestro/subscriptions.json
https://github.com/dotnet/arcade/blob/release/3.x has diverged too much from main for these PRs to make sense.  Changes should now be manually ported if at all.
> Remove arcade auto-PR from release/3.x to main

- build-info/docker/image-info.dotnet-dotnet-buildtools-prereqs-docker-main.json
This is the only remaining digest value that's not fully qualified.  I'm manually setting it to be fully-qualified in order to unblock the work for https://github.com/dotnet/docker-tools/issues/611.
> Fully-qualify the digest value in image info file

- build-info/docker/image-info.dotnet-dotnet-buildtools-prereqs-docker-main.json
The 5df5239 commit was made to both GitHub and AzDO but the GitHub commit somehow did not get associated with a branch.  This caused AzDO to have the commit but GitHub did not have it which is breaking the code-mirror build for this repo.  Fixing this by merging in the commit to the main branch.
> Merging buildtools changes

- Maestro/subscriptions.json
Should auto-merge `release/6.0-rc1`, `release/6.0-rc2`, and `release/6.0-ga` back to `release/6.0`. @mmitche does the syntax look right?
Will merge this just before 5 today
> Add auto-merge for aspnetcore release/6.0-rc*,ga*

- Maestro/subscriptions.json
Only `release/6.0` itself should merge to main. @mmitche syntax look right?
> Don't merge efcore 6.0/rc branches to main

- Maestro/subscriptions.json
Add Go `dev.boringcrypto` branches to the list to mirror internally.
`microsoft/dev.boringcrypto/**/*` mirrors `microsoft/dev.boringcrypto*` because:
* #558
/cc @qmuntal @chsienki @jaredpar
> Add Go 'microsoft/dev.boringcrypto*' mirroring

- Maestro/subscriptions.json
The dotnet-monitor project now has multiple active release branches that should be mirrored to their corresponding internal/* branches.
cc @dotnet/dotnet-monitor
> Mirror all dotnet-monitor release branches to internal branches.

- Maestro/subscriptions.json
> Remove auto merge dotnet/runtime release/6.0 -> release/6.0-maui

- Maestro/subscriptions.json
Source build works in the 1xx branch which can put us out of sync in servicing. Adding automatic flow from 1xx and 2xx up a level each.
> Add auto merge for the servicing branches of 6.0.Nxx

- Maestro/subscriptions.json
From discussions with @huangmin-ms  this is no longer desired and has been broken for some time.
> Remove mono/api-doc-tools

- Maestro/subscriptions.json
The subscriptions added with https://github.com/dotnet/versions/pull/808 are not appearing to run.  I think this is because the `vsoSourceBranch`  is not correctly specified.  My understanding is the `vsoSourceBranch` is the branch for where the action lives (e.g. arcade) not where the pr generator should run
> Fix broken github-dnceng-branch-merge-pr-generator subscription for sdk/installer

- Maestro/subscriptions.json
Removed the subscription entry that creates PR from release/3.1 -> main in WPF repo , as main ( 7.0 now ) and 3.1 have diverged.
There was a discussion last year regarding this in https://github.com/dotnet/wpf/pull/4164#issuecomment-781550340.
> Removed entry - release/3.1 to main in wpf repos

- Maestro/subscriptions.json
- We're no longer maintaining a main-vs-deps branch in the razor-tooling repo.
> Delete main-vs-deps subscription from razor-tooling repository

- Maestro/subscriptions.json
This was only used by the .NET Docker team's infrastructure. But that dependency has been removed as part of the work for https://github.com/dotnet/docker-tools/issues/986.
> Remove mirroring of versions repo

- Maestro/subscriptions.json
6.0.2xx goes out of support in May. The final changes should already be in the public repo. At this time, we should stop flowing changes from .1xx through .2xx and skip straight to .3xx.
> Skip .2xx from now on

- build-info/docker/image-info.dotnet-dotnet-buildtools-prereqs-docker-production.json
Now that the dotnet-buildtools/prereqs has a new `production` branch from which to build official images, we need a corresponding image info file for that branch. By default, it will be empty and then populated with metadata as new builds run from that branch.
> Image info for dotnet-buildtools/prereqs production branch

- build-info/docker/image-info.dotnet-dotnet-buildtools-prereqs-docker-production.json
The [logic in Image Builder](https://github.com/dotnet/docker-tools/blob/defad2c5d0b303dac5ab9a6046e88d8676a62037/src/Microsoft.DotNet.ImageBuilder/src/Commands/PublishImageInfoCommand.cs#L173-L223) doesn't handle the case of an empty repos array in the image info file very well. It thinks the merging behavior has caused all the data to be removed and throws an exception as a fail safe from accidentally removing unintended data.
The workaround is just to predefine the `dotnet-buildtools/prereqs` repo in the array.
> Predefine repo in new dotnet-buildtools/prereqs image info

- Maestro/subscriptions.json
Add CTP branch for automated tests and internal mirrors.
> Set up mirroring for the `ctp` branch of `dotnet/wpf`

- Maestro/subscriptions.json
Now that rc2 is out, 7.0 is a servicing branch.
> Remove 7.0 merges for asp.net

- Maestro/subscriptions.json
This is enabling mirroring support for https://github.com/dotnet/project-system. It should mirror `main` into https://dev.azure.com/devdiv/DevDiv/_git/dotnet-project-system.
> Mirror dotnet/project-system into DevDiv AzDO

- Maestro/subscriptions.json
Add AzDO mirroring for the dotnet/sign repository, cli branch only.
CC @MattGal
> Add dotnet/sign repo mirroring

- Maestro/subscriptions.json
7.0.2xx is going internal for servicing so adding it to the mirror
Created a new 7.0.3xx branch and adding it to the codeflow so code will go 7.0.2xx->7.0.3xx->main.
> Add 7.0.2xx to the mirror and 7.0.3xx to the codeflow

- Maestro/subscriptions.json
Explicitly chain MSBuild's servicing branches oldest->newest instead of having automation open everything->main and doing the chain manually.
cc @dotnet/msbuild-admins
> Automate MSBuild's merge chain

- Maestro/subscriptions.json
We created this `release/1.0.x`  branch
https://github.com/NuGet/PackageSourceMapper/tree/release/1.0.x
> Add release branches for PackageSourceMapper

- Maestro/subscriptions.json
We have a speculative branch of a new version of ICU with an alternative commit history, published to a branch on GitHub. We need to start mirroring this internally so we can test integration with downstream repositories.
> Add "test" branches to ICU mirror

- Maestro/subscriptions.json
Based on https://github.com/dotnet/versions/pull/835
The bot should automatically create PRs that backport everything from the (upcoming) staging branches:
- release/7.0-staging
- release/6.0-staging
into their respective base branches:
- release/7.0
- release/6.0
Then a human can manually merge the PR on code-complete day.
- The staging branches have not been created yet. Allow me to create them first, then we can merge this PR. cc @dotnet/dnceng because I'll need someone to help merge this when the time comes.
- The RC rules are not relevant anymore for .NET 6 and 7. We will eventually create a new rule for .NET 8 when the time comes. Let me know if you think I should bring them back for some reason.
cc @mmitche @ViktorHofer @ericstj @jeffhandley @akoeplinger @hoyosjs
> Add bot rule for auto dual check-in from dotnet/runtime staging to base servicing branches

- Maestro/subscriptions.json
We are locking down for 17.6 and main will become 17.7.
> MSBuild 17.6->16.7 merges

- Maestro/subscriptions.json
Mirroring is not working for the dotnet-extensions-experimental repo (reported on FR), the reason may be a wrong path
> Fix dotnet-extensions-experimental mirroring

- Maestro/subscriptions.json
17.7 is being locked down; development on 17.8 will continue in main
This is cc of the https://github.com/dotnet/versions/pull/875 PR
MSBuild vs17.6 (so far latest release branch) will now flow to vs17.7 (newest release branch from now on) and vs17.7 changes will flow to main
cc @rainersigwald as FYI
> MSBuild vs17.6->vs16.7 merges (aka 17.7 -> 17.8 from VS perspective)

- Maestro/subscriptions.json
We do not use the release/* pattern so replace it with rel/* that is actually used
> Mirror test-templates rel/* branches

- Maestro/subscriptions.json
This allows the [dotnet/workload-versions](https://github.com/dotnet/workload-versions) repo to be mirrored internally in Azure DevOps. It will mirror the `main` branch and any `release` branches.
> Add the dotnet/workload-version repo to code mirroring

- Maestro/src/Microsoft.DotNet.Maestro/Microsoft.DotNet.Maestro.csproj
Looks like this commit broke the world: https://github.com/dotnet/versions/commit/1077cf4c0f3a5e30a620518d283b3f4ef14e7515
Needed to provide some manual intervention to fix this project, because it's old and hasn't been migrated to use some of our more modern project infrastructure to keep versions consistent within a solution.
> Update package version in project

- Maestro/subscriptions.json
We are locking down for 17.8 and main will become 17.9.
> MSBuild 17.7 -> 17.8

- Maestro/subscriptions.json
Adding support to mirror any patch/* branches from vscode-csharp to the internal repo.  We'll be using the patch/* branches to release urgent out of band fixes to the C# extension that cannot go through the normal flow.
We do not use the prerelease branch any more, so that one is removed.
> Update vscode-csharp to mirror any patch/ branches

- Maestro/subscriptions.json
I noticed the code-mirror job on devdiv AzDO is failing for the source-build repo, looks like there's no internal repo anymore so removing the mirroring.
```
remote: TF401019: The Git repository with name or identifier dotnet-source-build-Trusted does not exist or you do not have permissions for the operation you are attempting.
fatal: repository 'https://dev.azure.com/devdiv/devdiv/_git/dotnet-source-build-Trusted/' not found
```
> Remove outdated source-build devdiv mirror

- Maestro/subscriptions.json
This adds the [dotnet/templating](https://github.com/dotnet/templating) repo to automatically flow the code between the release branches. The flow is:
- release/6.0.1xx -> release/6.0.3xx
- release/6.0.3xx -> release/6.0.4xx
- release/6.0.4xx -> release/7.0.1xx
- release/7.0.1xx -> release/7.0.3xx
- release/7.0.3xx -> release/7.0.4xx
- release/7.0.4xx -> release/8.0.1xx
- release/8.0.1xx -> release/8.0.2xx
- release/8.0.2xx -> main
> Add dotnet/templating to automatic release branch-to-branch codeflow

- Maestro/subscriptions.json
Same as with `7.0-staging` and `6.0-staging`, which was done in #872 and then in #873.
@ericstj @ViktorHofer @lewing @hoyosjs @steveisok @mmitche
> Automatic runtime dual check-in from `release/8.0` into `release/8.0-staging`

- Maestro/subscriptions.json
It was archived: https://github.com/dotnet/linker/pull/3238
/cc @mmitche
> Stop mirroring dotnet/linker main branch

- Maestro/subscriptions.json
The `github-dnceng-azdo-internal-merge-mirror` action is linked to the correct build definition: https://github.com/carlossanlop/versions/blob/ef97ed984ba3593524526644e0872f70bdb57e72/Maestro/subscriptions.json#L21-L26 
@ViktorHofer @ericstj @mmitche
> Mirror maintenance-packages main azdo branch to internal/main

- Maestro/subscriptions.json
We are adding 17.9 branch in MSBuild repo, [see #9484](https://github.com/dotnet/msbuild/issues/9484). Adjusting the flow.
> MSBuild 17.8 -> 17.9 -> main

- Maestro/subscriptions.json
We're going to be using the prerelease branch for creating builds, so needs to be mirrored to the internal repo.
> Add mirroring for the vscode-csharp prerelease branch

- Maestro/subscriptions.json
From email conversation on Jan 16, Orleans mirroring is no longer needed.
> Stop mirroring the orleans repository

- Maestro/subscriptions.json
Hi, I want to setup the auto sync from https://github.com/dotnet/roslyn-tools to its dnceng mirror https://dev.azure.com/dnceng/internal/_git/dotnet-roslyn-tools
> Auto sync roslyn-tool main to dnceng mirror

- Maestro/subscriptions.json
We are adding 17.10 branch in MSBuild repo, https://github.com/dotnet/msbuild/issues/9914. Adjusting the flow.
> MSBuild-17.9 -> 17.10

- .gitattributes
The default `JSON` language disallows comments, but they're really helpful in `subscriptions.json`.
Compare for example https://github.com/dotnet/versions/blob/9461cd023c450752070d7dc8f36f733c60fac13e/Maestro/subscriptions.json
with
https://github.com/rainersigwald/versions/blob/18af711f72ea66a5c056d787e4236dde5d28154b/Maestro/subscriptions.json
> Tell GitHub to not make JSON comments red

- Maestro/subscriptions.json
dotnet/iot is no longer building out of dnceng, so removing the mirror as we will remove the dnceng fork soon.
cc: @ericstj
> Remove dotnet/iot mirror

- Maestro/subscriptions.json
Aspire will no longer maintain the vNext branch, so we are disabling the mirror as well as the merge PRs from main
> Disabling aspire vNext subscriptions

- Maestro/subscriptions.json
so we don't need to include them in branch to branch flow anymore
> 7.0 and 8.0.2xx are out of support starting in June releases 

- Maestro/subscriptions.json
Internal mirror is disabled (not yet in use) so disable mirroring.
> Disable mirror of dotnet/maui

- Maestro/subscriptions.json
I actually didn't know that this had a public GH version. I've made all changes to the internal repo. Since this repo only exists for VS insertions, I'm not sure why it was created in GH at all so I'm going to archive the public GH repo and continue to work in the AzDO version.
> Remove insertions client from the mirror

- Maestro/subscriptions.json
I removed subscriptions which
- don't map to existing branches in GitHub
- repo in github doesn't exist
- repo in azdo doesn't exist
- repo in azdo is archived
Few smaller tweaks
Continuation of https://github.com/dotnet/versions/pull/973/
This is just based on my exploration, not authoritative. Let's bring in somebody who could validate.
> Remove obsolete dnceng mirroring entries (2)

- Maestro/subscriptions.json
Currently only `main` branch is active, hence there is no need in this functionality. 
Based on the discussion in PRs:
- https://github.com/aspnet/BrowserLink/pull/115
- https://github.com/aspnet/BrowserLink/pull/116
- https://github.com/dotnet/Scaffolding/pull/2818
- https://github.com/dotnet/Scaffolding/pull/2819
FYI @wtgodbe
> Remove the BrowserLink & Scaffolding subs to github inter-branch merge

- Maestro/subscriptions.json
The legacy inter-branch merge functionality is going to be deprecated soon. There is an effort in progress to transition to new InterBranch merge functionality based on GitHub actions. 
This item (subscription) to inter-branch merge using legacy flow is : 
Merge changes from `release/2.1` to `main`. 
There is no `main` branch in this repository: https://github.com/aspnet/BuildTools/branches, hence the merge flow will fail. 
FYI @wtgodbe
> Offboard buildTools from GitHub Merge Flow

- Maestro/subscriptions.json
The legacy inter-branch merge functionality is going to be deprecated soon. There is an effort in progress to transition to new InterBranch merge functionality based on GitHub actions.
This item (subscription) to inter-branch merge using legacy flow is :
Merge changes from `release/8.0-preview5` to `release/8.0`.
Based on the conversation: https://github.com/dotnet/aspire/pull/4609#discussion_r1647840549 
This flow from preview5 to release8 is no longer needed. 
FYI: @joperezr  @eerhardt
> Offboard dotnet/aspire not active sub

- Maestro/subscriptions.json
The legacy inter-branch merge functionality is going to be deprecated soon. There is an effort in progress to transition to new InterBranch merge functionality based on GitHub actions.
dotnet/arcade-services is already onboarded on the new inter-branch flow, hence removing it from the legacy flow. 
Onboarding PRs: 
https://github.com/dotnet/arcade-services/pull/3669
https://github.com/dotnet/arcade-services/pull/3668
New flow generated PRs: https://github.com/dotnet/arcade-services/pull/3681
FYI: @premun @oleksandr-didyk
> Offboard dotnet/arcade-services from legacy inter-branch merge flow

- Maestro/subscriptions.json
The PRs onboarding the dotnet/extensions repository are merged: https://github.com/dotnet/extensions/pull/5239
The run from main to dev: https://github.com/dotnet/extensions/actions/runs/9747690241/job/26900966700
Resulted PR: https://github.com/dotnet/extensions/pull/5256
FYI: @joperezr, @RussKie
> Offboard dotnet/extensions from inter-branch merge

- build-info/microsoft/go-images/image-info.microsoft-go-images-main.json
* See https://github.com/dotnet/versions/pull/987
* For https://github.com/microsoft/go/issues/157
It turns out that `"repos": []` isn't enough to seed the file, and we got this error in a build:
```
-- Calculating new image info content
Unhandled exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
---> System.InvalidOperationException: Removal of out-of-date content resulted in there being no content remaining in the target image info file. Something is probably wrong with the logic.
...
```
(From [PublishImageInfoCommand.cs#L217-L221](https://github.com/dotnet/docker-tools/blob/78d1b28945c95cfaea6cd01b6333500939fab552/src/Microsoft.DotNet.ImageBuilder/src/Commands/PublishImageInfoCommand.cs#L217-L221))
This PR adds the full …
> go-images image-info: populate full initial file
