- build-info/dotnet/cli/master/Latest_Packages.txt
Stop gap until https://github.com/dotnet/cli/issues/2999 is sorted.
> Add a Latest-Packages for rc3 \ preview2

- Maestro/subscriptions.json
> Add updatedependencies handler for corefx release branch.

- build-info/dotnet/roslyn/netcore1.0/Latest_Packages.txt
@joshfree, @eerhardt please review.
> Update to 1.3.0-beta1-20160606-02

- build-info/dotnet/symreader/netcore1.0/Latest_Packages.txt
@eerhardt, @tmat, @joshfree please review.
> Update Microsoft.DiaSymReader to 1.0.8

- Maestro/subscriptions.json
Adds blank build-info files to the versions repo. Replicated the CoreFX master subscriptions and adjusted for this branch.
/cc @eerhardt @danmosemsft @ellismg @stephentoub
> Add build-info and subscriptions for corefx dev/api branch

- Maestro/subscriptions.json
> Add subscriptions to automatically update coreCLR dependencies

- Maestro/subscriptions.json
/cc @eerhardt 
(To be reverted when https://github.com/dotnet/buildtools/issues/835 is done and flowed through.)
> Temporarily remove coreclr auto-updates

- Maestro/subscriptions.json
* corefx -> corefx
* projectk-rel -> corefx
* projectk-rel -> coreclr
/cc @wtgodbe @gkhanna79
> Add corefx/coreclr 1.0.0 auto-update subscriptions

- Maestro/subscriptions.json
"UpdateDependenices" alone has been changed to only update the files, to better match up target names to actions. Needs to be merged after https://github.com/dotnet/corefx/pull/10868, which takes the change.
/cc @eerhardt
> Rename "UpdateDependencies" target to add "AndSubmitPullRequest".

- Maestro/subscriptions.json
> Change CoreFX dev/api subscriptions to use new VersionTools auto-PR task

- Maestro/subscriptions.json
@dagood Could you please review.
FYI
@roncain @zhenlan @iamjasonp @mconnew @hongdai
> Plug-in wcf to Maestro.

- Maestro/build.cmd
- netci.groovy
/cc @eerhardt @dagood @mmitche
> Add Jenkins CI for building and running tests

- netci.groovy
> Escape backslashes in netci.groovy

- Maestro/build.cmd
> Restore packages in build.cmd

- Maestro/subscriptions.json
> Maestro handler to update docker-nightly rel-1.0.0-preview2.1 artifacts

- Maestro/subscriptions.json
Related to https://github.com/dotnet/dotnet-docker-nightly/pull/154
FYI - @rakeshsinghranchi, @vivmishra
> Update Docker subscription for CLI rel/1.0.0-rc3

- Maestro/subscriptions.json
/cc @eerhardt @piotrpMSFT @livarcocc
> Update CLI subscription to use the new rel/1.0.0 pipebuild

- Maestro/subscriptions.json
@eerhardt
FYI @ericstj @bryanar
> Add standard repo to the auto-update PRs for corefx and core-setup

- Maestro/subscriptions.json
CC @gkhanna79 @dagood - let's merge this at 6 PST tonight, 2/8/2017
> Disable per-PR builds of Core-Setup 1.1.0/1.0.0

- Maestro/subscriptions.json
@dagood @MichaelSimons @naamunds 
/cc @dotnet/dotnet-cli
> Update dependencies in cli master

- Maestro/subscriptions.json
Branches are stabilizing. /cc @gkhanna79
> Disable CI triggers for core-setup 1.0.0 and 1.1.0

- Maestro/subscriptions.json
@eerhardt @gkhanna79 @weshaggard PTAL.
> Add release/2.0.0 subscriptions for CoreFx, CoreCLR and Core-Setup.

- Maestro/subscriptions.json
> Add core-setup release 2.0.0 build trigger

- Maestro/subscriptions.json
> Add CLI release/2.0.0 update-dependencies.

- Maestro/subscriptions.json
Related to https://github.com/dotnet/dotnet-docker-nightly/issues/281
> Update Docker subscription to trigger on changes from cli release/2.0.0

- Maestro/subscriptions.json
Preparing for 2.0.0 final builds.
> Remove core-setup release/2.0.0 ci build trigger

- Maestro/subscriptions.json
> No longer trigger core-setup master builds through maestro

- build-info/dotnet/core-setup/master/Latest.txt
PTAL: @dagood 
Adding place holder Latest.txt file to core-setup master so that we can get latest package versions from corefx repo.
> Adding placeholder file to core-setup so that we can use the UpdateDependencies task in corefx

- Maestro/subscriptions.json
This is allow core-setup to receive auto-update PRs.
/cc @dagood @chcosta @weshaggard
> Add definition to update core-setup master

- Maestro/subscriptions.json
Enabling auto-upgrades for core-setup's dev/defaultintf branch
/cc: @dagood
> Adding a new subscription fro dev/defaultintf

- Maestro/subscriptions.json
Resolves https://github.com/dotnet/core-eng/issues/813 
/cc @dagood
> Update Maestro bot

- build-info/dotnet/cli/release/2.0.0/Last_Build_Packages.txt
- build-info/dotnet/cli/release/2.0.0/Latest.txt
- build-info/dotnet/cli/release/2.0.0/Latest_Packages.txt
Updating again to for latest preview 2 builds.
cc @livarcocc @dagood
> Updating build-info/dotnet/cli/release/2.0.0 for preview2-006479

- build-info/dotnet/cli/release/2.0.0/Last_Build_Packages.txt
- build-info/dotnet/cli/release/2.0.0/Latest.txt
- build-info/dotnet/cli/release/2.0.0/Latest_Packages.txt
Updating again for the latest preview2 build of CLI.
cc @livarcocc @dagood
> Updating build-info/dotnet/cli/release/2.0.0 for preview2-006494

- Maestro/subscriptions.json
Related to dotnet/dotnet-docker-nightly#398
> Add docker subscription for cli 2.1 dependencies

- Maestro/subscriptions.json
> Add triggers for mirroring our changes across branches in VSTS

- Maestro/subscriptions.json
> Add standard (master) repo subscription

- Maestro/subscriptions.json
> Set vsosourcebranch for standard subscrilption

- Maestro/subscriptions.json
> Subscribe corefx and core-setup to standard 2.0.0 release branch

- build-info/dotnet/corefx/release/2.0.0/Latest_Packages.txt
> Update Microsoft.NETCore.Platforms to latest in 2.0.0 release branch

- Maestro/subscriptions.json
cc: @weshaggard @dagood 
I can't merge in this repo, so if you approve, could you also please merge?
> Remove triggers for core-setup release builds

- Maestro/subscriptions.json
These changes are needed in response to [changes](https://github.com/dotnet/dotnet-docker-nightly/pull/548) made to the dotnet-docker-nightly update-dependencies tool.
> Update dotnet-docker-nightly subscriptions

- Maestro/subscriptions.json
This change depends on PR https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_git/DotNet-Orchestration-Utilities/pullrequest/105219?_a=overview and should not be merged before that one.
> Add FinalSymbolPublish target Maestro subscription.

- Maestro/subscriptions.json
@dotnet/dotnet-cli @eerhardt @dagood
> Adding release/2.1.1xx and release/2.1.2xx branches of the CLI to maestro

- Maestro/subscriptions.json
Related to https://github.com/dotnet/dotnet-docker-nightly/issues/525
> Update subscriptions per dotnet-docker-nightly merging into dotnet-docker

- Maestro/subscriptions.json
https://github.com/dotnet/coreclr/pull/16405
https://github.com/dotnet/corefx/pull/27180
https://github.com/dotnet/core-setup/pull/3698
https://github.com/dotnet/core-eng/issues/2435
> Add Core* auto-update triggers for release/2.1

- Maestro/subscriptions.json
> Add symbol publish trigger for 2.1-preview1 builds

- Maestro/subscriptions.json
Adds a new Maestro subscription for the uwp-setup repo. Adds triggers for the uwp-setup master branch and arm64 branch.
> Setup Maestro for uwp-setup repo

- Maestro/subscriptions.json
> Add arcade to github mirror

- Maestro/subscriptions.json
After merging this, I'll merge an otherwise-NOP change that triggers these.
> Add subscriptions for 2.1-preview1 publish

- Maestro/subscriptions.json
Resolves https://github.com/aspnet/aspnet-docker/issues/256
cc @dagood @MichaelSimons @ryanbrandenburg
> Subscribe aspnet-docker nightly to updates of release/2.1

- build-info/dotnet/projectn-tfs-ilc/arm64/Latest.txt
- build-info/dotnet/projectn-tfs-ilc/master/Latest.txt
https://github.com/dotnet/core-eng/issues/2749 should enable Maestro subscriptions to work on the uwp-setup repo.
> Update projectn-tfs-ilc master and arm64 Latest.txt to test Maestro

- build-info/dotnet/projectn-tfs-ilc/arm64/Latest.txt
- build-info/dotnet/projectn-tfs-ilc/master/Latest.txt
Per https://github.com/dotnet/core-eng/issues/2749, now tat the dotnet-maestro-bot fork is created, the auto-update should succeed.
> Trigger projectn-tfs-ilc master and arm64 builds once more.

- Maestro/subscriptions.json
Related to dotnet/dotnet-docker#396
> Add subscription to build dotnet-docker samples when source changes

- Maestro/subscriptions.json
Required per refactoring done with https://github.com/dotnet/dotnet-docker/pull/401
Related https://github.com/dotnet/dotnet-docker/issues/398
> Update dotnet-docker ScriptFileName

- Maestro/subscriptions.json
> Add aspnetcore dependencies update to MaestroBot

- Maestro/subscriptions.json
Replaces use of old mirror job
> Add mirroring for buildtools

- Maestro/subscriptions.json
Add Maestro mirroring triggers for CLI
> Add maestro mirroring triggers for CLI

- Maestro/subscriptions.json
Contingent on https://github.com/dotnet/corefx/pull/27987
@dagood PTAL
> Use UpdateDependencies.ps1 for CoreFX 1.1.x

- build-info/dotnet/projectn-tfs-ilc/release/uwp6.1/Latest.txt
Testing the new branch auto-PR flow but don't have a newer set of packages
> Force Maestro to submit a PR for uwp-setup release

- Maestro/subscriptions.json
> Fix syntax error in trigger params for aspnet-docker

- Maestro/subscriptions.json
In conjunction with my DotNet-Orchestration-Utilities PR.
> Add symbol publishing to both msdl and symweb.

- Maestro/subscriptions.json
Update Maestro subscriptions to trigger corefx release/uwp6.1 updates on corefx & coreclr release/uwp6.1 updates
> Update Maestro subscriptions to trigger corefx release/uwp6.1 updates

- Maestro/subscriptions.json
cc @ryanbrandenburg @mmitche @dagood
> Fix syntax error when invoking aspnet update scripts

- Maestro/subscriptions.json
> Add machinelearning release branches to github-vsts-mirror

- Maestro/src/Microsoft.DotNet.Maestro.WebApi/Web.config
- Maestro/src/Microsoft.DotNet.Maestro.WebApi/packages.config
- Maestro/src/Microsoft.DotNet.Maestro.WebJob/App.config
- Maestro/src/Microsoft.DotNet.Maestro/Config.cs
- Maestro/src/Microsoft.DotNet.Maestro/Microsoft.DotNet.Maestro.csproj
- Maestro/src/Microsoft.DotNet.Maestro/Services/VsoService.cs
- Maestro/src/Microsoft.DotNet.Maestro/packages.config
- Maestro/test/Microsoft.DotNet.Maestro.SubscriptionValidation/app.config
Also switch over to using MSI and KeyVault to grab secrets
> Support for multiple devdiv instances in maestro

- Maestro/src/Microsoft.DotNet.Maestro.WebApi/Controllers/CommitPushedController.cs
- Maestro/src/Microsoft.DotNet.Maestro.WebApi/Models/ModifiedFileModel.cs
- Maestro/src/Microsoft.DotNet.Maestro.WebApi/Models/SubscriptionsModel.cs
- Maestro/subscriptions.json
Tested End to End with merge commit 
1 - change pushed to the shared path in the corefx repo
2 - Maestro collects the data about the commit and trigger the corresponding vsts build definition
3- This build definition stores the relevant Info in the azure table.
4- Mirroring tools then opens the PR for these changes from a fork account.
Opening through Fork
https://github.com/dotnet/coreclr/pull/18527
https://github.com/dotnet/coreclr/pull/18527
> Subscription added fron gitSyncCommitManager

- Maestro/subscriptions.json
@mmitche , PTAL and merge
FYI @mikem8361
> Mirror dotnet/diagnostics into devdv.vs.com

- Maestro/subscriptions.json
> Update CLI subscriptions and final publishing for 2.1.401

- Maestro/subscriptions.json
Part of https://github.com/aspnet/Home/issues/3278 - we're going to be working in both release/2.2 and master branches for a while. This should help us prevent 2.2 and master from drifting too much.
Also, added triggers for aspnet/IISIntegration (cc @pakrym @jkotalik)
cc @chcosta @mmitche @muratg @Eilon
> Automatically create PRs to merge release/2.2 to master in aspnet repos

- Maestro/subscriptions.json
cc @natemcmaster @dagood @wtgodbe
> Add hook to automatically merge core repos release/2.1 to release/2.2 branches

- Maestro/subscriptions.json
> Add feature/utf8string branch to maestro

- Maestro/subscriptions.json
This reverts commit c7dd1f1d14abd17decbafdb712e65fea7cf323fb.
Also adds core-setup mirror
> Revert "Disable mirror for 2.1"

- Maestro/subscriptions.json
> Add config to have maestro open PRs to merge aspnet release/2.1 branches to release/2.2

- Maestro/subscriptions.json
> Add triggers for 2.2

- Maestro/subscriptions.json
FYI @natemcmaster @weshaggard I'm trying this out in source-build for infra changes.
> Add source-build 2.1 => 2.2 auto merge PR trigger

- Maestro/subscriptions.json
Made a mistake in my previous PR with the trigger path.
> Fix invalid trigger path for WCF Master subscription.

- Maestro/subscriptions.json
Part of https://github.com/dotnet/core-eng/issues/3974.
FYI @chcosta, I think I forgot about this earlier.
> Fix CoreFXLab subscription: post-refactor Core-SDK

- Maestro/subscriptions.json
> Add source-build 2.2 => master auto merge PR trigger

- Maestro/src/Microsoft.DotNet.Maestro.WebApi/Web.config
- Maestro/subscriptions.json
> Transition VSTS account name to dnceng

- Maestro/subscriptions.json
@mmitche, please review and merge
FYI @livarcocc
> Add dotnet-cli-archiver

- Maestro/subscriptions.json
Remove temporary final publish for 2.1.5/2.1.500
Add dependency update for 2.1.5 and 2.1.500
> Dependency update and cleanup

- Maestro/subscriptions.json
CC @natemcmaster 
Merge after https://github.com/dotnet/arcade/pull/992.
> Allow automated commits to aspnetcore

- Maestro/subscriptions.json
Also removed the out of date master triggers.
> Add 2.1.6 publish triggers

- Maestro/subscriptions.json
> Adding dotnet/iot repo to the internal mirror webhook

- Maestro/subscriptions.json
Changes in response to https://github.com/dotnet/dotnet-docker/pull/803
> Update Maestro subscription for changes to updating docker dependencies

- Maestro/subscriptions.json
> Mirror aspnet/AspNetCore to internal branches

- Maestro/subscriptions.json
I don't have the permissions to set the necessary WebHook on this repo (if one is needed). @natemcmaster, can you?
> Add aspnet/AspLabs to azdo mirror

- Maestro/subscriptions.json
> Add corefx triggers to dnceng mirror

- Maestro/subscriptions.json
The live service running in production should get mirrored too
> Add production branch to arcade-services

- Maestro/subscriptions.json
Adding the dotnet/test-templates repo to the list of repos in subscriptions.json
> Add dotnet/test-templates repo.

- Maestro/subscriptions.json
* During the adoption phase will be doing all the work out of the AdoptArcade branch before moving it into master.
Auto format removed the comma from line 835/836, I believe this is how it should be anyway, correct?
> Adding subscription of WCF branch for dnceng internal mirror.

- Maestro/subscriptions.json
CC. @dagood, @jkotas, @sbomer, @jashook, @hoyosjs 
This was no longer working due to https://github.com/dotnet/coreclr/pull/21608 as per https://github.com/dotnet/versions/pull/418#issuecomment-461186051
> Updating the subscription job for CoreCLR master branch.

- Maestro/subscriptions.json
setting up maestro for WPF release branches
> adding wpf release branches to maestro

- Maestro/subscriptions.json
This resolves https://github.com/dotnet/coreclr/issues/22646
CC. @dagood, @jkotas
> Updating coreclr-general/master to call the new eng\\update-dependencies.cmd script

- Maestro/subscriptions.json
> Remove source-build 2.2 => master auto merge

- Maestro/subscriptions.json
Reverts dotnet/versions#442
We'll do this weekly in AzDO instead
> Revert "Add auto-merge from Master into Release/3.0"

- Maestro/subscriptions.json
> Make PRs to merge aspnet's p4 branches back to master

- Maestro/subscriptions.json
> Add ML features branch to the mirror

- Maestro/subscriptions.json
As per @GrabYourPitchforks, we can now disable these dependency PRs for UTF8String. @dagood PTAL
> Disable dependency PRs for UTF8String feature branches

- Maestro/subscriptions.json
> Make PRs to merge aspnet's p5 branches back to master

- Maestro/subscriptions.json
> Add corefxlab mirror trigger

- Maestro/subscriptions.json
> Code-mirror aspnet/aspnet-docker

- Maestro/subscriptions.json
> Add dotnet/cli-lab to mirror

- Maestro/subscriptions.json
FYI @wtgodbe @mmitche - this mostly affects servicing
> Unify to single definition for generating branch merge PRs

- Maestro/subscriptions.json
aspnet/HttpRepl is being split off from aspnet/AspLabs
> Add subscription for aspnet/HttpRepl

- Maestro/subscriptions.json
@mmitche @nguerrera @marek-safar
> Mirror linker release branches

- Maestro/subscriptions.json
- no longer correct to merge directly into 'master'
> Merge aspnet/* 'release/2.2' -> 'release/3.0'

- Maestro/subscriptions.json
Part of https://github.com/aspnet/AspNetCore-Internal/issues/2976
CC @dougbu @JunTaoLuo 
@dagood can you merge (if this looks good)?
> Update ASP merge PRs to pull from preview9 branches

- Maestro/subscriptions.json
cc: @mmitche 
Adding release/3.0 branch for iot repo to the internal mirror.
> Add IoT release/3.0 branch to the internal mirror

- Maestro/subscriptions.json
- remove '3.0.0-preview9' merges
- add '3.1.0-preview1' merges
> Update ASP.NET Core merge configuration

- Maestro/subscriptions.json
- arcade: release/3.x -> master
- arcade-services: production -> master
- arcade-pool-provider: production -> master
- helix-service: production -> master
> Add inter-branch merges for arcade's repos

- Maestro/subscriptions.json
Replacing roslyn-tools bot with maestro bot for merge of CLI repos.
@rainersigwald @mmitche @livarcocc
> Auto merge cli branches

- Maestro/subscriptions.json
> Remove Asp.Net preview1 auto-merges

- Maestro/subscriptions.json
cc: @mmitche @dagood @ViktorHofer @jaredpar
> Add dotnet/runtime subscriptions for azure devops mirror

- Maestro/subscriptions.json
> Automate merging release/3.1 into blazor-wasm feature branches

- Maestro/subscriptions.json
Setting up internal mirror for VSCode extension for dotnetcore
cc @wli3
> Adding VSCode extension subscription

- Maestro/subscriptions.json
> Add SDK repos 3.1.1xx -> 3.1.2xx -> master

- Maestro/subscriptions.json
> Merge 3.1 -> blazor-wasm -> master in AspNet repos

- Maestro/subscriptions.json
Sorry, I missed this one on the previous PR.  cc @dagood @mmitche
> Remove source-build 3.0 => 3.1 auto-merge.

- Maestro/subscriptions.json
> Disable 3.0 -> 3.1 automerges during 3.0.2/3.1.1

- Maestro/subscriptions.json
/cc @dagood @wtgodbe @JunTaoLuo @Pilchie @anurse
> Do not merge ASP.NET through 'release/2.2'

- Maestro/subscriptions.json
I believe this is correct given the changes @Pilchie made earlier today. Probably can't be merged until we sort out the internal dotnet-extensions repo conflict.
Please note the various "Reviewers:" questions included in my changes. I'll remove them before final merge.
/cc @wtgodbe @JunTaoLuo @mmitche @Pilchie @anurse @ajcvickers @mkArtakMSFT @dagood
> React to new org for 6 ASP.NET Core repos

- Maestro/subscriptions.json
Remove 2.2 maestro subscriptions
> Temporary final publish for 2.1.15

- Maestro/subscriptions.json
> add dotnet/interactive mirror

- Maestro/subscriptions.json
> Remove branch merge from 3.1.1xx to 3.1.2xx

- Maestro/subscriptions.json
dotnet/toolset master is not in dotnet/sdk
@dsplaisted @wli3 @mmitche
> Remove obsolete merge subscription

- Maestro/subscriptions.json
> Merge release/5.0 branches to master for Asp.Net

- Maestro/subscriptions.json
We no longer want to do automatic merges into this branch.
CC @pranavkm @SteveSandersonMS @javiercn @Pilchie @dougbu @JunTaoLuo
> Disabling merging 3.1 -> blazor-wasm

- build-info/docker/image-info.Microsoft-dotnet-framework-docker-master.json
- build-info/docker/image-info.dotnet-dotnet-buildtools-prereqs-docker-master.json
- build-info/docker/image-info.dotnet-dotnet-docker-master.json
Related to https://github.com/dotnet/docker-tools/issues/438
> Upgrade image info files to new schema

- build-info/docker/image-info.Microsoft-dotnet-framework-docker-master.json
Related to https://github.com/dotnet/docker-tools/issues/438
> Upgrade image info for .NET Fx to new schema

- Maestro/subscriptions.json
> Add dev/infrastructure

- Maestro/subscriptions.json
New branch - need to mirror to dotnet Azure DevOps
> Enable mirroring of dotnet/deployment-tools

- Maestro/subscriptions.json
> Update EFCore triggers

- Maestro/subscriptions.json
> disable dependency flow into uwp 6.2

- Maestro/subscriptions.json
See https://github.com/dotnet/source-build-reference-packages/pull/137
> Mirror source-build-reference-packages pre-arcade branch

- Maestro/subscriptions.json
> Mirror the versions repo

- Maestro/subscriptions.json
> Update SDK interbranch merge from 3.1.1xx->3.1.2xx to 3.1.1xx->3.1.4xx

- Maestro/subscriptions.json
https://github.com/dotnet/core-eng/issues/10648
> Add mirroring for m2m-renaming-test-1

- Maestro/subscriptions.json
Renamed m2m-renaming-test-1 branch to main
> Renamed m2m-renaming-test-1 branch to main

- Maestro/subscriptions.json
> Add runtimelab gh to azdo mirror trigger

- Maestro/subscriptions.json
Fixes https://github.com/dotnet/core-eng/issues/11042
Don't @ people with every comment in merge PRs.
Note that this change applies to aspnetcore, extensions and efcore // @ajcvickers
> Quieten ASP.NET Core merging PRs

- Maestro/subscriptions.json
cc: @mmitche @jkotas @joperezr
> Add action to trigger runtime to runtimelab mirror also mirror runtimelab master to internal

- Maestro/subscriptions.json
/cc @dagood @mmitche @wtgodbe
/fyi @dotnet/aspnet-build @ericstj
> Remove dotnet/extensions 3.1 to master merges

- Maestro/subscriptions.json
> Merge aspnet servicing branches directly to main

- Maestro/subscriptions.json
- part of dotnet/aspnetcore#29475
> Handle new 'main' branch in dotnet/aspnetcore

- Maestro/subscriptions.json
Related to https://github.com/dotnet/docker-tools/issues/742
I have permission to merge.  I'll merge this on Monday.
> Update default branch of docker-tools

- Maestro/subscriptions.json
> Updating dotnet/iot branch subscription msater => main

- Maestro/subscriptions.json
changed master to main for dotnet/Scaffolding
> Updated subscriptions.json for dotnet/Scaffolding

- Maestro/subscriptions.json
master to main: https://github.com/microsoft/reverse-proxy/issues/709
cc: @dotnet/dnceng
> Update the build mirroring for reverse-proxy

- Maestro/subscriptions.json
- repo does not have 3.0 or 3.1 branches
> Merge aspnet/BuildTools 2.1 to master

- Maestro/subscriptions.json
WCF repo rename from master to main
> rename WCF repo from master to main

- Maestro/subscriptions.json
> Remove SDK code merge between 3.1.1xx and 3.1.4xx

- Maestro/subscriptions.json
> Update runtime-assets M2M

- Maestro/subscriptions.json
> Update runtimelab master to main

- Maestro/subscriptions.json
> Update the build mirroring for HttpRepl

- Maestro/subscriptions.json
> Update build mirroring for aspnet/browserlink

- Maestro/subscriptions.json
> mono/cecil master->main renaming

- Maestro/subscriptions.json
> mono/api-doc-tools master -> main renaming

- Maestro/subscriptions.json
> dotnet/deployment-tools master -> main renaming

- Maestro/subscriptions.json
> Migrating dotnet/crank to main branch

- Maestro/subscriptions.json
> M2M for dotnet/arcade

- Maestro/subscriptions.json
React to the branch being renamed in arcade https://github.com/dotnet/core-eng/issues/12145
Already created the branch https://dnceng.visualstudio.com/internal/_git/dotnet-arcade?version=GBmain
I plan to keep the master branch around for a bit so there's no rush on getting this in right away.
> Use the code mirroring pipeline from main

- Maestro/subscriptions.json
> Add mirroring for mono/mono.posix repo

- Maestro/subscriptions.json
> Change master to main for mono/mono

- Maestro/subscriptions.json
Changed master to main for machinelearning.
> Updated subscriptions

- Maestro/subscriptions.json
> Change project system tools to main

- Maestro/subscriptions.json
Sending this out now as the ci queue is long. This includes the change for sdk as well as that was already in my fork.
> Marcpop msft updateinstaller

- Maestro/subscriptions.json
> Add mirroring for dotnet/emsdk repo

- Maestro/subscriptions.json
This is part of https://github.com/dotnet/cssparser/issues/6.
cc @dnceng
> Change cssparser 'master' to 'main' in subscriptions.json

- Maestro/subscriptions.json
> Switch branch for msbuild language service and nuget.buildtasks repos

- Maestro/subscriptions.json
> Update default branch for aspnet/BuildTools

- Maestro/subscriptions.json
@dotnet/dnceng please merge this
> M2M CliCommandLineParser

- Maestro/subscriptions.json
https://github.com/dotnet/arcade/issues/7119
> m2m renaming of arcade-validation

- Maestro/subscriptions.json
/cc @wtgodbe @RussKie @dotnet/wpf-developers
> Change windowsdesktop master to main in subscriptions.json

- Maestro/subscriptions.json
Arcade-services' branch was renamed a couple of days ago.
> Fix dnceng services auto PR from production to main

- Maestro/subscriptions.json
- mirror GitHub ➡️ AzDO for all 'main' and 'release' branches
- mirror all 'release' branches ➡️ `internal/release/*` in AzDO
> Add aspnet-AspNetWebStack mirroring

- Maestro/subscriptions.json
- want internal/ branches in AspNetWebStack
- don't need this in AspNetWebHooks right now
> Fix typo from #753

- Maestro/subscriptions.json
Adding subscriptions to create merge PRs in winforms-designer repo:
1. release/16.10p4 to release/16.11p1
2. release/16.11 preview branches to main
> Merge PR subscriptions for winforms-designer repo

- Maestro/subscriptions.json
> Add dotnet-monitor feature branch mirroring

- Maestro/subscriptions.json
> Add dotnet/msquic to internal mirror paths

- Maestro/subscriptions.json
> Add merge bot for release/6.0-rc1 into release/6.0

- Maestro/subscriptions.json
(Will update the Arcade sub to push into release/6.0.2xx once this is done.)
> Add razor-compiler release/6.0.2xx to main merges

- Maestro/subscriptions.json
No longer needed, we're doing manual backport
> Remove 6.0.2xx automerge

- Maestro/subscriptions.json
Adds mirroring to dnceng for nuget/packageSourceMapper's dev branch
> add nuget/packageSourceMapper mirroring for dev branch

- Maestro/subscriptions.json
> Revert "Add test for ubuntu mirroring to test real workflow"

- Maestro/subscriptions.json
ClrMD changed master -> main, and that needs to be reflected here.
> Update ClrMD subscription

- Maestro/subscriptions.json
- also remove old 6.0.x merges of aspnetcore
> Add spa-templates mirroring

- Maestro/subscriptions.json
Use https://devdiv.visualstudio.com/DevDiv/_build?definitionId=16952, an arcade-based pipeline, for devdiv.visualstudio code mirroring tasks
https://github.com/dotnet/arcade/issues/10159
> Update DevDiv code mirror pipeline job

- Maestro/subscriptions.json
@dotnet/dnceng @mmitche please approve and merge
> Add 7.0 dual check-in bot for dotnet/runtime

- Maestro/subscriptions.json
Adds auto-merges from rel/7.0-rc* to rel/7.0, and rel/7.0 to main.
> Add auto-merges for aspnetcore 7.0 branches

- Maestro/subscriptions.json
- ensure official builds use the latest
> Mirror AspNetWebHooks-Signed

- Maestro/subscriptions.json
Re-enable mirror of Versions repo to dnceng
> Enable mirroring of versions repo

- Maestro/subscriptions.json
We need to mirror this branch as well
> Add dotnet-buildtools-prereqs-docker production branch to mirror

- Maestro/subscriptions.json
Add cecil main branch to the azure mirror subscription
> Add cecil subscription to subscriptions.json

- Maestro/subscriptions.json
> Add dotnet/maintenance-packages to maestro mirror

- Maestro/subscriptions.json
The cli branch will merge into the main branch.
> Update dotnet/sign subscription

- Maestro/subscriptions.json
https://github.com/dotnet/arcade/issues/13226
> Add dotnet/dnceng-shared to code mirroring

- Maestro/subscriptions.json
Related issue: https://github.com/dotnet/arcade/issues/13308
> Adding dotnet/dnceng to mirror config

- Maestro/subscriptions.json
> Mirror https://github.com/dotnet/extensions@main

- Maestro/subscriptions.json
Part of FR request to mirror https://github.com/Azure/dotnet-extensions-experimental
> add mirror for dotnet-extensions-experimental repo

- Maestro/subscriptions.json
https://github.com/dotnet/dnceng/issues/170
> Adding dotnet/dnceng production branch to Maestro mirror

- Maestro/subscriptions.json
Automatically generate PRs to merge changes from main to dev branch for dotnet/extensions.
> Merge changes in dotnet/extensions from main to dev

- Maestro/subscriptions.json
No longer takes updates from an internal runtime
> Remove internal merge mirroring for templating

- Maestro/subscriptions.json
> Mirror https://github.com/dotnet/extensions@dev

- Maestro/subscriptions.json
Automatically merging changes that go into aspire's main branch to vNext branch as well.
> Enable automatic merges for aspire main -> vNext

- Maestro/subscriptions.json
> Automatically open PRs to merge release/8.0-preview5 to release/8.0 in aspire

- Maestro/subscriptions.json
See https://github.com/dotnet/versions/pull/714
> Mirror new repository

- Maestro/subscriptions.json
See also https://github.com/dotnet/runtimelab/pull/2620 and https://github.com/dotnet/runtimelab/pull/2617
cc @jkotas @mmitche
> disable code flow for runtimelab

- build-info/microsoft/go-images/image-info.microsoft-go-images-main.json
* Redo of https://github.com/dotnet/versions/pull/782
* For https://github.com/microsoft/go/issues/157
@gdams 
/cc @mthalman @lbussell
> Seed the microsoft/go-images image-info file

- Maestro/subscriptions.json
see: https://github.com/dotnet/templating/pull/8155#issuecomment-2193795518
cc @marcpopMSFT
> Remove Legacy Inter-Branch Merge from dotnet/templating

- Maestro/subscriptions.json
Offboard inactive repos.
- dotnet/razor-compiler: Archived (https://github.com/dotnet/razor-compiler?tab=readme-ov-file#-razor-compiler-is-archived-)
- dotnet/winforms-designer: removed
> Offboard inactive repos

- build-info/docker/image-info.dotnet-dotnet-docker-main.json
Related:
- https://github.com/dotnet/dotnet-docker/pull/6547
- https://github.com/dotnet/dotnet-docker-internal/issues/7409
> Synchronize Dockerfile commit URLs
